- .dockerignore
- .github/workflows/build.yml
- Frontend/organisation-app/Dockerfile
- Makefile
- compose.common.yml
- compose.yml
The Dockerfile is constructed from multiple stages:
* base - installs all system dependencies
* dependencies - installs application dependencies
* source - bundles application source code
* build - packages the application as static files
* dev - runs the application in development mode
* serve - serves the application packages as static files
Docker compose mounts the `Frontend/organisation-app` as a volume, so it's possible to use this setup for development.
If you have the `compose.override.yml` file locally, you'll need to either remove it so it's re-generated, or add the following section under `services`:
```
organisation-app:
ports:
- "${CDP_ORGANISATION_APP_PORT:-3000}:3000"
```
> CDP-22: Add the organisation-app to docker compose services

- .dockerignore
- Frontend/organisation-app/.gitignore
- compose.common.yml
An improvement over #2
`npm ci` always starts fresh, which is good for reproducible builds, but bad for performance. Using the cache directory makes it slightly faster. This way node_modules can be ignored from the Docker context again.
> Improve speed of `npm ci` on Docker

- compose.common.yml
Before we got the repository and the project named, I bootstrapped it on my local machine calling it "organisation information". Since we're calling it "Central Digital Platform" now, I thought it would be good to update names of our Docker containers and images.
> Rename image and container names to match the project name

- Makefile
- README.md
In order to prevent selected service(s) from starting, configure the number of replicate in `compose.override.yml` to 0:
```yaml
services:
organisation-app:
ports:
- "${CDP_ORGANISATION_APP_PORT:-80}:8080"
environment:
- ASPNETCORE_ENVIRONMENT=Development
deploy:
replicas: 0
```
> Document the process of preventing a service from starting

- Frontend/CO.CDP.OrganisationApp.Tests/SessionTest.cs
- Frontend/CO.CDP.OrganisationApp/Session.cs
Here's how the Session can be tested without mocking the 3rd party type, for reasons explained in https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/18#issuecomment-1999813018.
While refactoring I found an additional case where the HTTP context might be null, which beautifully proves the point.
> Refactor session tests to avoid mocking a 3rd party type

- docs/decisions/0002-create-webapi-clients.adoc
- docs/decisions/index.adoc
I considered three options and put forward my recomendation. Please give feedback and let me know if there's anything I haven't considered.
One option for client generation I didn't explore is https://github.com/OpenAPITools/openapi-generator.
For better reviewing experience, GitHub can render the document on the PR when you "view the file": https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/blob/6ffc419b3276dc66fe46d9705fe1254d631d3b99/docs/decisions/0002-create-webapi-clients.adoc
> Decide how to create webapi clients

- Dockerfile
- Makefile
- README.md
- compose.common.yml
- compose.yml
An alternative to #34 #44.
This PR introduces a database migrations container. It includes a self-contained migrations bundle that is able to execute database migrations given a connection string.
> Build a dedicated migrations container

- Frontend/CO.CDP.OrganisationApp/CO.CDP.OrganisationApp.csproj
- README.md
Secrets can be either set in the IDE, or in the secrets manager (documented in the README).
This way, there's less chance of committing secrets to the repository than when secrets are given in files that are normally version controlled.
> Configure and document onelogin secrets

- Services/CO.CDP.Organisation.WebApi/Program.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseTenantRepositoryTest.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/PostgreSqlFixtureExtensions.cs
- Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
- Services/CO.CDP.Person.WebApi/Program.cs
- Services/CO.CDP.Tenant.WebApi/Program.cs
* make the constructor accept DbContextOptions as recommended in documentation instead of the connection string
* move the choice of database out of our custom db context
* make it easier to construct the db context for the postgres docker container
> Tidy database context

- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseTenantRepositoryTest.cs
Resolve warnings in DatabasePersonRepositoryTest & DatabaseTenantRepositoryTest
> Fix dereference of a possibly null reference in repo tests

- Dockerfile
- GCGS-Central-Digital-Platform.sln
- Libraries/CO.CDP.Swashbuckle.Tests/CO.CDP.Swashbuckle.Tests.csproj
- Libraries/CO.CDP.Swashbuckle.Tests/Filter/ProblemDetailsOperationFilterTest.cs
- Libraries/CO.CDP.Swashbuckle/CO.CDP.Swashbuckle.csproj
- Libraries/CO.CDP.Swashbuckle/Filter/ProblemDetailsOperationFilter.cs
- Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
- Services/CO.CDP.DataSharing.WebApi/CO.CDP.DataSharing.WebApi.csproj
- Services/CO.CDP.DataSharing.WebApi/Program.cs
* Document DataSharing error responses
* Convert exceptions to `ProblemDetails` responses (in DataSharing)
```csharp
builder.Services.AddProblemDetails();
```
* Provide a library for documenting `ProblemDetails` examples (CO.CDP.Swashbuckle)
It can be added to the application by:
```csharp
builder.Services.AddSwaggerGen(options => options.OperationFilter<ProblemDetailsOperationFilter>() }
```
As a result, responses that use ProblemDetails will be documented with examples:
> Document error responses (data sharing API)

- Frontend/CO.CDP.OrganisationApp/Properties/launchSettings.json
- README.md
- Services/CO.CDP.DataSharing.WebApi/DataSharing.http
- Services/CO.CDP.DataSharing.WebApi/Properties/launchSettings.json
- Services/CO.CDP.Forms.WebApi/Forms.http
- Services/CO.CDP.Forms.WebApi/Properties/launchSettings.json
- Services/CO.CDP.Organisation.WebApi/Organisation.http
- Services/CO.CDP.Organisation.WebApi/Properties/launchSettings.json
- Services/CO.CDP.Person.WebApi/Person.http
- Services/CO.CDP.Person.WebApi/Properties/launchSettings.json
- Services/CO.CDP.Tenant.WebApi/Properties/launchSettings.json
- Services/CO.CDP.Tenant.WebApi/Tenant.http
- compose.yml
This change lowers the friction to mix services started with Docker and an IDE.
During development, testing, or debugging it's often useful to run some services with Docker,
while others with an IDE.
To do that, first start all the services with Docker. Remember to override environment variables for services
that you plan to run in an IDE:
```bash
OrganisationService=http://host.docker.internal:8082 docker compose up -d
```
In the above example, we pointed the Organisation service to the one we plan to start with the IDE.
`host.docker.internal` is used to connect from Docker containers to the host machine.
Next, stop selected services in Docker:
```bash
docker compose stop organisation
```
Finally, start the selected services in the IDE.
> Align IDE ports with docker compose defaults

- Dockerfile
Currently, a change in one project that's copied earlier will invalidate projects copied later. With this PR, every csproj file is treated as an independent layer.
See https://docs.docker.com/reference/dockerfile/#copy---link
> Copy project files with --link to prevent unnecessary invalidation when previous layers change

- Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs
- Services/CO.CDP.Tenant.WebApi/Model/TenantLookup.cs
```json
{
"user": {
"urn": "urn:fdc:gov.uk:2022:43af5a8b-f4c0-414b-b341-d4f1fa894302",
"name": "John Doe",
"email": "john@example.com"
},
"tenants": [
{
"id": "826def77-311c-424d-a86e-069029c859c0",
"name": "Acme Corporation / John Doe",
"organisations": [
{
"id": "f4596cdd-12e5-4f25-9db1-4312474e516f",
"name": "Acme Group Ltd",
"roles": [
"Buyer"
],
"uri": "https://cdp.cabinetoffice.gov.uk/organisations/f4596cdd-12e5-4f25-9db1-4312474e516f",
"scopes": [
"Responder"
]
}
]
}
]
}
```
> DP-128: Include organisation scope in the tenant lookup response

- terragrunt/modules/core-iam/ci-datasource.tf
- terragrunt/modules/ecs-service/listeners.tf
- terragrunt/modules/ecs-service/variables.tf
- terragrunt/modules/ecs/load-balancer.tf
- terragrunt/modules/ecs/service-data-sharing.tf
- terragrunt/modules/ecs/service-forms.tf
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/ecs/service-organisation.tf
- terragrunt/modules/ecs/service-person.tf
- terragrunt/modules/ecs/service-tenant.tf
- terragrunt/modules/ecs/task-organisation-information-migrations.tf
[DP-1](https://noticingsystem.atlassian.net/browse/DP-1)
This will allow HTTP access to all services via **supplier.information.findatender.codatt.net** domain, i.e.:
- http://tenant.dev.supplier.information.findatender.codatt.net/swagger
- http://organisation.dev.supplier.information.findatender.codatt.net/swagger
- http://person.dev.supplier.information.findatender.codatt.net/swagger
- http://forms.dev.supplier.information.findatender.codatt.net/swagger
- http://data-sharing.dev.supplier.information.findatender.codatt.net/swagger
- http://organisation-app.dev.supplier.information.findatender.codatt.net
> DP-1 Wire up subdomains to corresponding services

- terragrunt/modules/ecs-service/listeners.tf
- terragrunt/modules/ecs-service/locals.tf
- terragrunt/modules/ecs-service/variables.tf
- terragrunt/modules/ecs/route53.tf
- terragrunt/modules/ecs/service-organisation-app.tf
[DP-1](https://noticingsystem.atlassian.net/browse/DP-1)
This will create [dev.supplier.information.findatender.codatt.net](https://dev.supplier.information.findatender.codatt.net) alias and link it to the **organisation-app**, _aka frontend_.
Similar to the existing [organisation-app.dev.supplier.information.findatender.codatt.net](https://organisation-app.dev.supplier.information.findatender.codatt.net/)
> DP-1 Create and link the domain alias to organisation-app

- terragrunt/modules/ecs-service/variables.tf
- terragrunt/modules/ecs/locals.tf
- terragrunt/modules/ecs/service-data-sharing.tf
- terragrunt/modules/ecs/service-forms.tf
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/ecs/service-organisation.tf
- terragrunt/modules/ecs/service-person.tf
- terragrunt/modules/ecs/service-tenant.tf
- terragrunt/modules/ecs/task-organisation-information-migrations.tf
At the moment there is no recognition of Staging (or any other account name related) environment to allow presenting swagger UI. 
So even in the Staging account we need to mark `ASPNETCORE_ENVIRONMENT` as Development
> DP-1 Set the service environmnet names to wither prod or dev

- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
[DP-1](https://noticingsystem.atlassian.net/browse/DP-1) 
- Use subdomains to address linked services, instead of the load-balancer's DNS and service port
> DP-1 Use subdomains to address linked services

- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
- Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
- Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs
Not ideal, but unblocks error handling on the UI side.
> Throw a DuplicateOrganisationException if the tenant is already registered for the organisation

- Services/CO.CDP.OrganisationInformation.Persistence/Migrations/OrganisationInformationContextModelSnapshot.cs
- Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'OrganisationPerson.Scopes' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'OrganisationPerson.Scopes' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
The property 'OrganisationPerson.Scopes' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
```
> Remove the warning when generating a migration

- terragrunt/modules/api-gateway/acm.tf
- terragrunt/modules/api-gateway/api-ecs.tf
- terragrunt/modules/api-gateway/api-root.tf
- terragrunt/modules/api-gateway/locals.tf
- terragrunt/modules/api-gateway/main.tf
- terragrunt/modules/api-gateway/outputs.tf
- terragrunt/modules/api-gateway/route53.tf
- terragrunt/modules/api-gateway/templates/landing-page.html.tftpl
- terragrunt/modules/api-gateway/variables.tf
- terragrunt/modules/ecs/variables.tf
Updating API Gateway:
- Add a page in root with links to all endpoints 
- split Root and ECS related resources into different files
- add an output for the API's domain
- Apply terraform format on all modules 
This has been applied in [staging](https://api.staging.supplier.information.findatender.codatt.net/).
> DP-1 Add landing page with links to endpoints

- Services/CO.CDP.Tenant.WebApi.Tests/UseCase/LookupTenantUseCaseTest.cs
- Services/CO.CDP.Tenant.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Fix the inconsistency between Windows and Linux relating to Uri, hard-code the host URL until we decide on the best way to specify the mapping for each environment.
> DP-168 Tenant Lookup fix URi test (windows)

- Frontend/CO.CDP.OrganisationApp/Program.cs
Otherwise, the app doesn't know it's behind https.
> Handle X-Forwarded-* headers in the organisation app

- docs/index.adoc
> Increase toc level to 3

- Libraries/CO.CDP.Swashbuckle/Filter/ProblemDetailsOperationFilter.cs
```
2024-07-02 15:23:10.885
An unhandled exception has occurred while executing the request.
2024-07-02 15:23:10.885
at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
2024-07-02 15:23:10.885
at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
2024-07-02 15:23:10.885
at CO.CDP.Swashbuckle.Filter.ProblemDetailsOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /src/Libraries/CO.CDP.Swashbuckle/Filter/ProblemDetailsOperationFilter.cs:line 99
2024-07-02 15:23:10.885
at CO.CDP.Swashbuckle.Filter.ProblemDetailsOperationFilter.UpdateExamples(KeyValuePair`2 operationResponse, Func`2 …
```
> Prevent same example being added multiple times

- Makefile
- terragrunt/modules/ecs/service-authority.tf
- terragrunt/modules/ecs/templates/task-definitions/authority.json.tftpl
This has been applied to [dev environment](https://dev.supplier.information.findatender.codatt.net/)
A fresh build also has been deployed to the account.
I can confirm [the authority service](https://authority.dev.supplier.information.findatender.codatt.net/swagger/index.html) is up and running
> DP-230 Remove authority's public key from infra

- Makefile
- compose.common.yml
- compose.yml
The localstack service will need to be added to `compose.override.yml` to provide port mapping:
```yaml
localstack:
ports:
- "4566:4566"
- "4510-4559:4510-4559"
deploy:
replicas: 1
```
Once started with `docker compose up -d localstack`, it can be tested with `awslocal`:
```bash
awslocal sqs create-queue --queue-name foo
awslocal sqs list-queues
awslocal sqs send-message --queue-url http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/foo --message-body '{"foo":"bar"}'
awslocal sqs receive-message --queue-url http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/foo
```
> Set up localstack for sqs and s3 services in local development

- .github/workflows/build.yml
- Makefile
Git commit can be used to ensure we only build each version once.
The following command can be used to generate a unique prefix of the commit (unique within the repository):
```bash
git rev-parse --short HEAD
```
We can use it for the main Docker tag, and then define additional alias tags once they are created, i.e.  `1.2.5-02e0c8b`, `1.2.5`.
The "Determine version" step [defines the main Docker tag](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/actions/runs/9909877385/job/27378962882?pr=278#step:3:20) that is tied to the git commit hash, as well the application version (that is based on the latest tag and git commit).
> Generate a version for Docker images

- Libraries/CO.CDP.MQ.Tests/PublisherContractTest.cs
- Libraries/CO.CDP.MQ.Tests/Sqs/SingleQueueMessageRouterTest.cs
- Libraries/CO.CDP.MQ.Tests/Sqs/SqsPublisherTest.cs
- Libraries/CO.CDP.MQ/IPublisher.cs
- Libraries/CO.CDP.MQ/Sqs/SingleQueueMessageRouter.cs
- Libraries/CO.CDP.MQ/Sqs/SqsPublisher.cs
- Services/CO.CDP.EntityVerification/Extensions/ServiceCollectionExtensions.cs
- Services/CO.CDP.EntityVerification/Ppon/OrganisationRegisteredEventHandler.cs
Routes all messages to the single queue. First time it's invoked, it finds the queue url based on the configured queue name.
In order to:
* remove asking for the queue url from the boostrap phase
* delay asking for the queue url
* reuse
The publisher can now be async.
> Introduce a single queue message router

- Services/CO.CDP.Forms.WebApi/CO.CDP.Forms.WebApi.csproj
- Services/CO.CDP.Forms.WebApi/Program.cs
- Services/CO.CDP.Organisation.Authority/CO.CDP.Organisation.Authority.csproj
- Services/CO.CDP.Organisation.Authority/Program.cs
- Services/CO.CDP.Organisation.WebApi/CO.CDP.Organisation.WebApi.csproj
- Services/CO.CDP.Organisation.WebApi/Program.cs
- Services/CO.CDP.Person.WebApi/CO.CDP.Person.WebApi.csproj
- Services/CO.CDP.Person.WebApi/Program.cs
- Services/CO.CDP.Tenant.WebApi/CO.CDP.Tenant.WebApi.csproj
- Services/CO.CDP.Tenant.WebApi/Program.cs
Adds a db check on health check action, a simple `SELECT 1` by default.
Testing:
1. call `/health` to confirm service is healthy
2. kill the db `docker kill co-cdp-db`
3. call `/health` to confirm service reports as unhealthy
> DP-308: Add db query to the health checks

- Services/CO.CDP.DataSharing.WebApi/Program.cs
- Services/CO.CDP.EntityVerification/Program.cs
- Services/CO.CDP.EntityVerification/appsettings.Development.json
- Services/CO.CDP.EntityVerification/appsettings.json
- Services/CO.CDP.Forms.WebApi/appsettings.Development.json
- Services/CO.CDP.Forms.WebApi/appsettings.json
- Services/CO.CDP.Organisation.WebApi/Program.cs
- Services/CO.CDP.Organisation.WebApi/appsettings.Development.json
- Services/CO.CDP.Organisation.WebApi/appsettings.json
- Services/CO.CDP.Person.WebApi/Program.cs
- Services/CO.CDP.Person.WebApi/appsettings.Development.json
- Services/CO.CDP.Person.WebApi/appsettings.json
- Services/CO.CDP.Tenant.WebApi/Program.cs
- Services/CO.CDP.Tenant.WebApi/appsettings.Development.json
- Services/CO.CDP.Tenant.WebApi/appsettings.json
A simple feature flag implemented with `appsettings.*.json`:
```json
"Features": {
"SwaggerUI": false
}
```
SwaggerUI has been enabled on `Development` builds and disabled on production builds.
> DP-200: Add feature flag for SwaggerUI in Services

- docker/localstack/ready.d/create-queues.sh
Once the message was delivered 10 times being explicitly removed, it will be move to the dead-letter queue.
Example log from when the queues are created:
```
co-cdp-localstack  | Creating the ev-outbound queue...
co-cdp-localstack  | 2024-08-02T08:03:36.157 DEBUG --- [et.reactor-0] l.services.sqs.provider    : creating queue key=ev-outbound-deadletter attributes=None tags=None
co-cdp-localstack  | 2024-08-02T08:03:36.157  INFO --- [et.reactor-0] localstack.request.aws     : AWS sqs.CreateQueue => 200
co-cdp-localstack  | 2024-08-02T08:03:36.354  INFO --- [et.reactor-0] localstack.request.aws     : AWS sqs.GetQueueAttributes => 200
co-cdp-localstack  | 2024-08-02T08:03:36.547 DEBUG --- [et.reactor-0] l.services.sqs.provider    : creating queue key=ev-outbound attributes={'RedrivePolicy': …
```
> DP-408: Create a dead-letter queue for each regular queue

- Services/CO.CDP.Organisation.Authority/TokenService.cs
DP-210 - UtcNow fix for PostrgreSQL error: Cannot write DateTimeOffset with Offset=01:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported.  (Parameter 'value')
> DP-210 - UtcNow fix for PostrgreSQL error

- Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml
[DP-387](https://noticingsystem.atlassian.net/browse/DP-387)
Displays "PPON generation pending." in org details page when there are no identifiers (including PPON) for an organisation.
> Bug: DP-387

- terragrunt/components/service/ecs/terragrunt.hcl
- terragrunt/components/terragrunt.hcl
- terragrunt/modules/core-iam/terraform-datasource.tf
- terragrunt/modules/orchestrator/ci/buildspecs/deployment.yml
- terragrunt/modules/orchestrator/ci/codebuild.tf
This has been provisioned and tested in the **orchestrator** account, successfully triggering the migration tasks in **development**. 
Additional changes, including granting permissions to retrieve different account IDs, will be made in a separate PR.
> DP-529 Add post-build phase to execute migration step-functions

- terragrunt/modules/ecs/templates/task-definitions/entity-verification-migrations.json.tftpl
- terragrunt/tools/grafana/README.md
- terragrunt/tools/grafana/configs/dashboards/application/logs-entity-verification-migrations.json
- Bring live service in line with [DP-391](https://noticingsystem.atlassian.net/browse/DP-391) changes [here](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/commit/ea00820bc70deb959853c8aed533f8a67e0799aa#diff-3493e6b5ddf34891e572f911db893efd9e46af828e011ea778a7c1eb64763588R104)
- Add Grafana dashboard for EV migrations
- Rename Grafana migration dashboards
> DP-529 Fix EV migration lacking Org-Auth address

- Frontend/CO.CDP.OrganisationApp.Tests/FormsEngineTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/DynamicFormsPageModelTest.cs
- Frontend/CO.CDP.OrganisationApp.Tests/Pages/ShareInformation/ShareCodeConfirmationTests.cs
- Frontend/CO.CDP.OrganisationApp/FormsEngine.cs
- Frontend/CO.CDP.OrganisationApp/IFormsEngine.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml.cs
- Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodeConfirmation.cshtml.cs
#dp-271 generate share code refactor.
> #dp-271 generate share code refactor

- Makefile
0.1.1 is always seen as latest otherwise.
> Fix getting the latest tag

- terragrunt/components/service/database/terragrunt.hcl
- terragrunt/modules/core-iam/outputs.tf
- terragrunt/modules/core-iam/rds-datasource.tf
- terragrunt/modules/core-iam/rds.tf
- terragrunt/modules/core-iam/terraform-datasource.tf
- terragrunt/modules/database/locals.tf
- terragrunt/modules/database/rds-entity-verification.tf
- terragrunt/modules/database/rds-sirsi.tf
- terragrunt/modules/database/variables.tf
- terragrunt/modules/rds/rds.tf
- terragrunt/modules/rds/variables.tf
Enable/Control RDS Features Across Environments
- Added support for automated backups
- Enabled Multi-AZ configuration
- Introduced storage auto-scaling
- Enabled Enhanced Monitoring
- Integrated Performance Insights
- Read-replica (resource added but not activate/provisioned)
- Storage type (kept the current default)
Tested in staging; now prepared for production and integration environments.
> DP-531 Add Switch for RDS Production Configuration

- terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl
- Added logic to correctly construct Slack notification links based on version string format.
- Implemented conditional checks for commit vs. release tag links.
- Simplified the state machine for better readability and reliability.
This has been tested in the orchestrator account and confirmed the following two type of links:
- `https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/0.4.0` for **0.4.0**
- `https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/commit/40fd0960` for **0.4.0-40fd0960**
> DP-564 Handle Version Strings with and without Hyphens

- Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
- Services/CO.CDP.DataSharing.WebApi/Program.cs
#dp-456 Add Authorization issue fixed for Share information
1.  500 error is in Organisation app
2.  in Data sharing Onelogin policy not found
Inside program.cs
For  replace:
builder.Services.AddAuthorization();
with:
builder.Services.AddOrganisationAuthorization();
> #dp-456 Add Authorization issue fixed for Share information

- Services/CO.CDP.DataSharing.WebApi.Tests/DataService/DataServiceTests.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/DataSharingFactory.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataPdfUseCaseTests.cs
- Services/CO.CDP.DataSharing.WebApi/DataService/DataService.cs
- Services/CO.CDP.DataSharing.WebApi/DataService/IDataService.cs
- Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataPdfUseCase.cs
This way clients of DataService will have less collaborators to work with as there's no need for them to use the repository to fetch SharedConsent first. Makes tests and client code simpler.
This:
```csharp
Task<SharedSupplierInformation> GetSharedSupplierInformationAsync(SharedConsent sharedConsent);
```
becomes:
```csharp
Task<SharedSupplierInformation> GetSharedSupplierInformationAsync(string shareCode);
```
This:
```csharp
var sharedConsent = await shareCodeRepository.GetByShareCode(sharecode);
if (sharedConsent == null)
{
throw new ShareCodeNotFoundException(Constants.ShareCodeNotFoundExceptionMessage);
}
var sharedSupplierInfo = await dataService.GetSharedSupplierInformationAsync(sharedConsent);
```
becomes:
```csharp
var sharedSupplierInfo = await …
```
> DP-455: Cleanup the DataService

- terragrunt/tools/grafana/configs/dashboards/application/logs-authority.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-data-sharing.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-entity-verification-migrations.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-entity-verification.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-forms.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-grafana.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-app.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-information-migrations.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-organisation.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-person.json
- terragrunt/tools/grafana/configs/dashboards/application/logs-tenant.json
The record timestamp is expected first.
The record title is expected second.
The level field is expected to be called `level` in order for the visualisation to add colours to the record.
https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/logs/#supported-data-formats
Before:
After:
> DP-222: Change the order of fields in Grafana dashboards

- Libraries/CO.CDP.AwsServices/CloudWatchExtensions.cs
Uses `RenderedCompactJsonFormatter` instead of `CompactJsonFormatter` to log a rendered message, rather than a template message.
> DP-222: Use RenderedCompactJsonFormatter for logging

- terragrunt/components/core/networking/terragrunt.hcl
- terragrunt/components/core/security-groups/terragrunt.hcl
- terragrunt/components/orchestrator/canary/terragrunt.hcl
- terragrunt/components/orchestrator/ecr/terragrunt.hcl
- terragrunt/components/service/api-gateway/terragrunt.hcl
- terragrunt/components/service/auth/terragrunt.hcl
- terragrunt/components/service/database/terragrunt.hcl
- terragrunt/components/service/ecs/terragrunt.hcl
- terragrunt/components/service/queue/terragrunt.hcl
- terragrunt/components/service/telemetry/terragrunt.hcl
- terragrunt/components/terragrunt.hcl
- terragrunt/modules/ecs-service/listeners.tf
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/orchestrator/canary/datasource.tf
- terragrunt/modules/orchestrator/canary/locals.tf
- terragrunt/modules/orchestrator/canary/main.tf
- terragrunt/modules/orchestrator/canary/variables.tf
- terragrunt/modules/rds/rds.tf
- terragrunt/modules/rds/variables.tf
- terragrunt/tools/canary/src/python/canary_check_api.py
- `canary_schedule_expression` for each account is the only addition in the root's terragrunt configuration
- Reformat
> DP-532 Allow different schedual for different accounts

- Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/ThirdPartyApiClients/CompaniesHouseApiTests.cs
- Frontend/CO.CDP.OrganisationApp/Constants/FlashMessageTypes.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Shared/_FlashMessage.cshtml
- Frontend/CO.CDP.OrganisationApp/ThirdPartyApiClients/CompaniesHouse/CompaniesHouseApi.cs
[DP-614](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-614)
> DP-614: Added notification message if CH not found or if company already registered

- terragrunt/components/terragrunt.hcl
Ensure that the number of instances in production-like accounts is limited to 1. While services are not sharing authentication sessions, maintain the same instance limit across both production-like and non-production accounts to allow for smooth deployment.
> DP-663 Keep only 1 task running for now

- Makefile
We were only checking if a service has exited with non-zero exit code. Now we also check if it's actually healthy when running.
> Check if running services are healthy (unless they are stopped)

- terragrunt/README.md
- terragrunt/modules/ecs/datasource.tf
- terragrunt/modules/ecs/service-organisation.tf
- terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
- Pass it to the the organisation service
-
> DP-589 Add temporary secret for support admin email address

- Frontend/CO.CDP.OrganisationApp.Tests/CustomScopeHandlerTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/TagHelpers/GovukButtonTagHelperTests.cs
- Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/DataSharingFactory.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetShareCodeVerifyUseCaseTest.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataDocumentDownloadUrlUseCaseTests.cs
- Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
- Services/CO.CDP.DataSharing.WebApi/UseCase/GetShareCodeVerifyUseCase.cs
- Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataDocumentDownloadUrlUseCase.cs
- Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataUseCase.cs
- Services/CO.CDP.OrganisationInformation.Persistence/DatabaseShareCodeRepository.cs
- Services/CO.CDP.OrganisationInformation.Persistence/IShareCodeRepository.cs
API Permission - No need for organisation id match for organisation key
> API Permission - No need for organisation id match for organisation key

- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseAuthenticationKeyRepositoryTest.cs
I noticed these tests sometimes fail.
It turns out it's due to one missing `await` call and fixtures shared between test cases.
Testcontainers are only started once per test class. It's a compromise that make tests run faster. The drawback is data created in a previous test case can affect next ones. It's important each test case creates a unique data set. We do have a solution for this (starting a transaction that's rolled back at the end), but we only use it as a last resort.
> Make repository tests less likely to fail due to parallel runs

- Services/CO.CDP.EntityVerification/appsettings.json
- Services/CO.CDP.Organisation.WebApi/appsettings.json
Otherwise it takes too long for the message to be published.
We will explore using LISTEN/NOTIFY later to reduce the need for pulling the messages.
> DP-712: Make more frequent calls to check if new messages were published

- Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseAuthenticationKeyRepositoryTest.cs
Otherwise, the test might fail randomly if the method returns before the `Save` call completes.
> Add a missing await call to let the call finish before the test completes

- Dockerfile
This target contributes to no other layer and isn't really needed.
> Remove an unnecessary build target

- Services/CO.CDP.Organisation.WebApi.Tests/UseCase/CreateOrganisationJoinRequestUseCaseTest.cs
- Services/CO.CDP.Organisation.WebApi/UseCase/CreateOrganisationJoinRequestUseCase.cs
- Services/CO.CDP.Organisation.WebApi/appsettings.json
- Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs
- Services/CO.CDP.OrganisationInformation.Persistence/IOrganisationRepository.cs
https://noticingsystem.atlassian.net/browse/DP-689
> DP-689: Registration - Request to Join Organisation- Notify 

- terragrunt/tools/grafana/configs/dashboards/overview/service-logs.json
- terragrunt/tools/grafana/configs/dashboards/overview/status-code-hits.json
- Include Healthcheck request filter into Status Code Hits dashboard
- Override filed colours: 
- Pie Chart all gray (since field names are different) 
- Trend's Legend Colour-coded 2xx, 3xx, etc.
This should help us to identify 5xxs easier and notice any spike during or after deployment of new versions
> DP-729 Add panel visualising status codes trend

- Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
- Libraries/CO.CDP.Forms.WebApiClient.Tests/FormsClientIntegrationTest.cs
- Libraries/CO.CDP.Organisation.WebApiClient.Tests/OrganisationClientIntegrationTest.cs
- Services/CO.CDP.Forms.WebApi.Tests/Api/DeleteFormAnswerSetEndpointTest.cs
- Services/CO.CDP.Forms.WebApi.Tests/Api/GetFormSectionQuestionsTest.cs
- Services/CO.CDP.Forms.WebApi.Tests/Api/GetFormSectionstEndpointTest.cs
- Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationEndpointsTests.cs
- Services/CO.CDP.Organisation.WebApi.Tests/Api/SupplierInformationEndpointsTests.cs
- Services/CO.CDP.Tenant.WebApi.Tests/Api/TenantLookupTest.cs
- TestKit/CO.CDP.TestKit.Mvc/FakePolicyEvaluator.cs
- TestKit/CO.CDP.TestKit.Mvc/HostBuilderExtensions.cs
- TestKit/CO.CDP.TestKit.Mvc/ServiceCollectionExtensions.cs
- TestKit/CO.CDP.TestKit.Mvc/TestWebApplicationFactory.cs
This way the application factory is more reusable as it does not make any assumptions about the application.
> Do not configure the fake policy evaluator by default

- Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/JoinOrganisationSuccessTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/JoinOrganisationTests.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/JoinOrganisation.cshtml
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/JoinOrganisation.cshtml.cs
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/JoinOrganisationSuccess.cshtml
- Frontend/CO.CDP.OrganisationApp/Pages/Registration/JoinOrganisationSuccess.cshtml.cs
Without at least the Viewer permission for an organisation, the user does not have access to call the `GetOrganisationAsync` endpoint. This code fixes that by switching to use `LookupOrganisationAsync` instead.
> Use identifier and lookup for all join request screens.

- Services/CO.CDP.Organisation.WebApi.Tests/UseCase/CreateOrganisationJoinRequestUseCaseTest.cs
- Services/CO.CDP.Organisation.WebApi/UseCase/CreateOrganisationJoinRequestUseCase.cs
While demoing I noticed the wrong name was displayed for the email that goes out to org admins: 
This was because the template was using the same name variables:
The template has been updated: 
and this PR contains the corresponding code to pass in the person who is making the org join request
> Bugfix - Notify: Fix wrong name being displayed in email.

- Frontend/CO.CDP.OrganisationApp/Program.cs
- Prototype/CompanyHouseApi.Integration/Program.cs
- Services/CO.CDP.DataSharing.WebApi/Program.cs
- Services/CO.CDP.EntityVerification/Program.cs
- Services/CO.CDP.Forms.WebApi/Program.cs
- Services/CO.CDP.Organisation.Authority/Program.cs
- Services/CO.CDP.Organisation.WebApi/Program.cs
- Services/CO.CDP.Person.WebApi/Program.cs
- Services/CO.CDP.Tenant.WebApi/Program.cs
- terragrunt/tools/healthcheck-service/healthCheck/Startup.cs
All services are running behind a load balancer that is responsible for ssl termination. There is no need to do https redictions as all services are always behind https.
> DP-761: Disable the HTTPS redirection middleware

- terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl
Add delay to ensure CodeBuild job in development updates to STARTED state before progressing to SUCCEEDED
> DP-819 Wait a second after updateding the source message

- Services/CO.CDP.Organisation.WebApi.Tests/UseCase/CreateOrganisationJoinRequestUseCaseTest.cs
- Services/CO.CDP.Organisation.WebApi/UseCase/CreateOrganisationJoinRequestUseCase.cs
DP-826 - Rejoin Organisation after being rejected
> DP-826 - Rejoin Organisation after being rejected

- terragrunt/components/orchestrator/common/terragrunt.hcl
- terragrunt/components/orchestrator/notification/terragrunt.hcl
- terragrunt/modules/ecs-service/listeners.tf
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/orchestrator/canary/variables.tf
- terragrunt/modules/orchestrator/common/datasource.tf
- terragrunt/modules/orchestrator/common/locals.tf
- terragrunt/modules/orchestrator/common/outputs.tf
- terragrunt/modules/orchestrator/common/ssm.tf
- terragrunt/modules/orchestrator/common/variables.tf
- terragrunt/modules/orchestrator/notification/cloudwatch.tf
- terragrunt/modules/orchestrator/notification/datasource.tf
- terragrunt/modules/orchestrator/notification/step-function.tf
- terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl
- terragrunt/modules/orchestrator/notification/variables.tf
- terragrunt/modules/tools/secrets.tf
- Include application version deploying to each account
- Add orchestrator/common component, holding SSM for all envs versions
- Remove target triggered by service-version parameter update
**Before:**
**After:**
**Step-function changes:**
> DP-837 Improve deployment notifications

- Frontend/CO.CDP.OrganisationApp/Authentication/OidcEvents.cs
- Frontend/CO.CDP.OrganisationApp/Program.cs
- Frontend/CO.CDP.OrganisationApp/appsettings.AwsProduction.json
- Frontend/CO.CDP.OrganisationApp/appsettings.json
dp-866 One login error logging
> dp-866 One login error logging

- Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRemoveConfirmation.cshtml
DP-912 - Clicking the Back link on the Connected Persons remove page leads to a Page Not Found error.
> DP-912 - Clicking the Back link on the Connected Persons remove page leads to a Page Not Found error.

- terragrunt/components/service/cache/terragrunt.hcl
- terragrunt/modules/core-iam/terraform-global-datasource.tf
- terragrunt/modules/core-iam/terraform-product-data-datasource.tf
- terragrunt/modules/core-iam/terraform-product-datasource.tf
- terragrunt/modules/core-iam/terraform.tf
- terragrunt/modules/core-networking/outputs.tf
- terragrunt/modules/core-security-groups/cache.tf
- terragrunt/modules/core-security-groups/outputs.tf
- terragrunt/modules/elasticache/cloudwatch.tf
- terragrunt/modules/elasticache/datasource.tf
- terragrunt/modules/elasticache/locals.tf
- terragrunt/modules/elasticache/outputs.tf
- terragrunt/modules/elasticache/redis.tf
- terragrunt/modules/elasticache/secrets.tf
- terragrunt/modules/elasticache/variables.tf
- terragrunt/modules/externals/networking/outputs.tf
- terragrunt/providers.tf
- Provisioned a secret holding the Redis authentication token.
- Split the product's IAM policy and included the ElastiCache-specific policy.
- Added a Security Group for the ElastiCache cluster.
- Created CloudWatch log groups for cache’s engine and slow logs.
- Configured log delivery for both engine and slow logs.
- Upgraded the AWS provider version.
> DP-925 Provision ElastiCache replication group, within private subnets using new module

- terragrunt/modules/ci/codebuild-update-account.tf
- terragrunt/modules/ci/codebuild-update-ecs-services.tf
- terragrunt/modules/orchestrator/ci/codebuild.tf
- While deployment jobs for existing components typically take about 2 minutes per account, provisioning new heavy components (such as Elasticache in this case) can take significantly longer.
- The increased timeout is intended to accommodate these rare situations and does not imply that we expect such durations during normal day-to-day operations.
> BAU: Increase build timeout by 15 minutes

- terragrunt/components/service/ecs/terragrunt.hcl
- terragrunt/components/terragrunt.hcl
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
- terragrunt/modules/ecs/variables.tf
- Added the `OneLoginLogoutNotificationUrls` environment variable to support logout notification forwarding.
- Configured different values for different accounts as per requirements.
The outcome has been tested in development and can confirm is as per the request:
> DP-889 Add OneLoginLogoutNotificationUrls env_var with account-specific values

- terragrunt/modules/ecs/datasource.tf
- terragrunt/modules/ecs/iam.tf
We would like to merge small, unblocker PRs even thought the full functionality is not in place yet. (More details in [this thread ](https://goacoglobal.slack.com/archives/C06M34UGL59/p1733243497005579))
This one has been proven in development, for new parameter has been created once new instances came up and their value were populated successfully.
> DP-925 Allow application to manage its own EC token for Data Protection

- Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
- Libraries/CO.CDP.Organisation.WebApiClient.Tests/CO.CDP.Organisation.WebApiClient.Tests.csproj
- Libraries/CO.CDP.Organisation.WebApiClient.Tests/OrganisationClientIntegrationTest.cs
- Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationEndpointsTests.cs
- Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
- Services/CO.CDP.Organisation.WebApi/Model/Command.cs
- Services/CO.CDP.Organisation.WebApi/UseCase/RegisterOrganisationUseCase.cs
dp-937 Update POST /organisations to use the logged in user rather than the one passed in the payload
> Update POST /organisations to use the logged in user rather than the one passed in the payload

- .github/workflows/build.yml
Each container we built will now be scanned for vulnerabilities with Grype.
Since there are existing vulnerabilities on base docker containers, I did not opt to fail the build if vulnerabilities are found, since it would hinder development. I also opted to only run these scans on the main branch and for tags.
Vulnerabilities are reported on GitHub and are hidden from the public: https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/security/code-scanning?query=pr%3A1008+is%3Aopen
> DP-972: Configure vulnerability scans for docker images

- .mise.toml
- terragrunt/modules/core-iam/terraform-global-datasource.tf
- terragrunt/modules/core-iam/terraform-product-datasource.tf
- terragrunt/modules/core-networking/locals.tf
- terragrunt/modules/core-networking/waf.tf
- terragrunt/providers.tf
Also upgrade Tools and Providers
We are including more managed rules than defined in the ticket, while keeping the capacity bellow 1500 which impact the cost.
- [Common](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html#aws-managed-rule-groups-baseline-crs)
- [Amazon IP Reputation (& Anonymous IP)](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-ip-rep.html#aws-managed-rule-groups-ip-rep-amazon)
- [Bot Control](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-bot.html#aws-managed-rule-groups-bot-rules)
- [SQL Injection](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-use-case.html#aws-managed-rule-groups-use-case-sql-db)
Once integrated with the load balance …
> DP-1002 Provision WAF & include its required IAM permissions

- terragrunt/README.md
- terragrunt/docs/manage-secrets.md
- terragrunt/modules/ecs/datasource.tf
- terragrunt/modules/ecs/locals.tf
- terragrunt/modules/ecs/service-organisation-app.tf
- terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
- Document (with `uuidgen` as an option)
- Rename `one_login` to `one_login_credentials` for clarity
> DP-1006 Add `OneLogin__ForwardLogoutNotificationApiKey`

- Frontend/CO.CDP.OrganisationApp.Tests/AuthorizationTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/ContentSecurityPolicyTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/LocalizationTests.cs
Otherwise, tests try to connect to redis that is unavailable.
Based on Authorization tests, before:
2min 42sec (locally)
After:
17sec (locally)
Github actions build, before:
After:
> Disable shared sessions in frontend tests

- Services/CO.CDP.DataSharing.WebApi/Program.cs
- Services/CO.CDP.EntityVerification/Program.cs
- Services/CO.CDP.Forms.WebApi/Program.cs
- Services/CO.CDP.Organisation.Authority/Program.cs
- Services/CO.CDP.Organisation.WebApi/Program.cs
- Services/CO.CDP.Person.WebApi/Program.cs
- Services/CO.CDP.Tenant.WebApi/Program.cs
Cherry-picked from https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/1075
Also applied in other projects, not only in EntityVerification and Organisation.WebApi.
This is the way that's recommended by npgsql. It will enable us to configure postgres enums properly.
> DP-712: Use the DataSource rather than a connection string to configure the database

- Frontend/CO.CDP.OrganisationApp.Tests/FtsUrlServiceTests.cs
- Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
- Frontend/CO.CDP.OrganisationApp/Constants/FeatureFlags.cs
- Frontend/CO.CDP.OrganisationApp/FtsUrlService.cs
- Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
- Frontend/CO.CDP.OrganisationApp/Session.cs
- Frontend/CO.CDP.OrganisationApp/appsettings.AwsIntegration.json
- Frontend/CO.CDP.OrganisationApp/appsettings.json
DP-1035 Dynamic FTS return URLs for integration environment
> DP-1035 Dynamic FTS return URLs for integration environment

- Services/CO.CDP.DataSharing.WebApi/appsettings.Development.json
- Services/CO.CDP.DataSharing.WebApi/appsettings.json
- Services/CO.CDP.EntityVerification/appsettings.Development.json
- Services/CO.CDP.EntityVerification/appsettings.json
- Services/CO.CDP.Forms.WebApi/appsettings.Development.json
- Services/CO.CDP.Forms.WebApi/appsettings.json
- Services/CO.CDP.Organisation.Authority/appsettings.Development.json
- Services/CO.CDP.Organisation.Authority/appsettings.json
- Services/CO.CDP.Organisation.WebApi/appsettings.Development.json
- Services/CO.CDP.Organisation.WebApi/appsettings.json
- Services/CO.CDP.Person.WebApi/appsettings.Development.json
- Services/CO.CDP.Person.WebApi/appsettings.json
- Services/CO.CDP.Tenant.WebApi/appsettings.Development.json
- Services/CO.CDP.Tenant.WebApi/appsettings.json
This brings the number of connections down so that we do not exceed the number in the pool.
Performance tests will reveal if this is sufficient or requires further tweaks.
Builds on top of #1032 and #1037
> DP-989: Reduce the default number of database connections in the pool to 10

- terragrunt/modules/database/locals.tf
- terragrunt/modules/database/rds-entity-verification.tf
- terragrunt/modules/database/rds-sirsi.tf
- terragrunt/modules/ecs/locals.tf
- terragrunt/modules/ecs/service-authority.tf
- terragrunt/modules/ecs/service-data-sharing.tf
- terragrunt/modules/ecs/service-entity-verification.tf
- terragrunt/modules/ecs/service-forms.tf
- terragrunt/modules/ecs/service-organisation.tf
- terragrunt/modules/ecs/service-person.tf
- terragrunt/modules/ecs/service-tenant.tf
- terragrunt/modules/ecs/task-migrations.tf
- terragrunt/modules/ecs/templates/task-definitions/authority.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/data-sharing.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/entity-verification-migrations.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/entity-verification.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/forms.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/organisation-information-migrations.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/person.json.tftpl
- terragrunt/modules/ecs/templates/task-definitions/tenant.json.tftpl
- terragrunt/modules/ecs/variables.tf
- Switch Staging to new Clusters
This has been tested in staging and [at first glance all seems shiny ](https://goacoglobal.slack.com/archives/C06JCFY3VFC/p1736516924254019?thread_ts=1736514447.471709&cid=C06JCFY3VFC)
> DP-979 Add mechanism to switch DB connection per environment

- Services/CO.CDP.AntiVirusScanner/appsettings.json
Unable to see av-scanner app log in Grafana. This should fix this issue.
> DP-1037 - corrected CloudWatch config for av-scanner.

- Libraries/CO.CDP.MQ.Tests/Outbox/OutboxProcessorTest.cs
- Libraries/CO.CDP.MQ/Outbox/OutboxProcessor.cs
A new postgres NOTIFY might arrive before the previous one was processed. To reduce the likelihood of publishing the same message more than once, the OutboxProcessor now uses a lock. 
If OutboxProcessor is run twice in short span of time, the second run will wait for a short time, and then give up. It's fine to give up, as the current run will handle all messages anyway.
The functionality is still disabled. To enabled it, the `OutboxListener` feature flag needs to be set to `true` in the `Organisation.WebApi` and `EntityVerification` projects.
> DP-712 Lock the outbox processor to ensure messages are only processed once

- Libraries/CO.CDP.AwsServices/Sqs/SqsDispatcher.cs
- Libraries/CO.CDP.MQ.Tests/DispatcherContractTest.cs
- Libraries/CO.CDP.MQ.Tests/Hosting/DispatcherBackgroundServiceTest.cs
- Libraries/CO.CDP.MQ/Hosting/DispatcherBackgroundService.cs
In order to reduce the lifetime of DbContext and flush db operations on each dispatcher run.
> DP-1202: reduce the scope of sqs dispatcher

- terragrunt/components/terragrunt.hcl
- Reduced `redis_node_type` from `cache.r5.12xlarge` to `cache.r5.4xlarge`
- Adjusted production instance count from 9 to 6
- Decreased production ECS resource allocation (`cpu: 4096 → 1024`, `memory: 8192 → 2048`)
These changes aim to balance performance with cost-effectiveness while ensuring production stability.
> DP-1299 Downsize Redis and ECS resource allocation for production

- E2ETests/compose.yml
- Makefile
- compose.yml
- Prevent overwriting the override file by default    
- Add force overwrite target    
- Remove  from the network's name
Once this PR is in, a one of removal of the old network will be required (just to keep local stack tidy)
```
docker network rm cdp-sirsi-network
```
_The other option can be running `make down` before fetching latest main and `make up` once pull latest_
> DP-1261 Override should not be phoney

- Makefile
(Note: they're still checked in the pipeline via the "Test migrations" command which runs "make db")
> Exclude migration containers from verify up

- terragrunt/components/terragrunt.hcl
Reverts cabinetoffice/GCGS-Central-Digital-Platform#1591
> Revert "Temporarily pin dev to 1.0.65 while tagging branch for integration to stop accidental deploys"

- terragrunt/modules/ecs/service-fts.tf
- It seems not only it doesn't have a health-check endpoint, but also it's landing page forces a redirect to search
> DP-1474 Temporary fix for FTS healthcheck URI

- terragrunt/components/service/notification/terragrunt.hcl
- terragrunt/components/terragrunt.hcl
- terragrunt/modules/notification/datasource.tf
- terragrunt/modules/notification/locals.tf
- terragrunt/modules/notification/main.tf
- terragrunt/modules/notification/outputs.tf
- terragrunt/modules/notification/route53.tf
- terragrunt/modules/notification/variables.tf
- Updated SES identity, DKIM, and Route53 resources to use `for_each` for better multi-domain support.
- Introduced `mail_from_domains` variable as a list to support future extension.
- Ensured backward compatibility: existing records remain untouched.
- Outputs now expose verification records and DKIM tokens per domain for external consumption.
> DP-1692 Refactor SES domain verification to support multiple mail-from domains

- terragrunt/components/service/ecs/terragrunt.hcl
- terragrunt/components/terragrunt.hcl
- terragrunt/modules/ecs/locals-cfs.tf
- terragrunt/modules/ecs/locals-fts.tf
- terragrunt/modules/ecs/service-cfs.tf
- terragrunt/modules/ecs/variables.tf
- Add support for extra host headers `cfs_extra_domains` (split `fts_extra_domains`)
- Update site and cookie domains for CFS
- Enable domain handling for www-preview and www-integration subdomains
- Prepare ECS modules and variables to accept traffic from non-owned domains
> CFS-Migration Support external domain redirects for staging and integration

- terragrunt/modules/core-iam/terraform-global-ses-datasource.tf
- terragrunt/modules/core-iam/terraform-product-datasource.tf
- terragrunt/modules/notification/datasource.tf
- terragrunt/modules/notification/locals.tf
- terragrunt/modules/notification/main.tf
- terragrunt/modules/notification/sns.tf
- terragrunt/modules/notification/sqs.tf
- terragrunt/modules/notification/variables.tf
- Created dedicated SES configuration set for logging
- Added SNS topic and policy allowing SES to publsh events
- Added SQS queue and DLQ as buffer
- Subscribed SQS to SNS topic
- Added SES event destination to configuration set for specified event types
- Updated IAM policies to allow managing SES config sets, and required SNS/SQS actions
- Introduced variables for logging event types
> DP-1712 Add SES JSON logging via SNS and SQS

- terragrunt/components/service/ecs/terragrunt.hcl
- terragrunt/modules/ecs/datasource.tf
- terragrunt/modules/ecs/service-fts-healthcheck.tf
- terragrunt/modules/ecs/templates/task-definitions/fts-healthcheck.json.tftpl
- terragrunt/modules/ecs/variables.tf
- terragrunt/modules/notification/outputs.tf
- terragrunt/tools/healthcheck-fts-service/README.md
- terragrunt/tools/healthcheck-fts-service/php/ses-test.php
- Added a proof-of-concept email send form and handler to the healthcheck service
- Allows testing SES email sending with optional configuration set from environment variable
- Prints debug output including region, sender, recipient, and config set in use
- To be replicated in the actual FTS service after validation
> DP-1712 Add SES email send POC to PHP healthcheck service

- terragrunt/modules/ecs/service-commercial-tools-api.tf
- terragrunt/modules/ecs/service-commercial-tools-app.tf
- We must revert this, once in the next release, they get their own release tags in line with other services
> CDPDEL-702 Pin commercial tools services to version 1.0.78-3bd90b215
