README.md
docs/decisions/0001-record-architecture-decisions.adoc
docs/decisions/index.adoc

Let's start logging important design decisions that were made during development.
The design decision log accomplishes the following goals:
* Provide a structured approach to decision-making.
* Explain to current and future developers why things are the way that they are.
* Help to revise decisions when the situation changes.

Bootstrap the decision log

---

Services/DataSharing/Api/DataSharing.cs

Updated DataSharing API to match its design (OpenAPI), ensuring data sharing works as intended (CRUD). 
This involved model adjustments, clearer endpoints, and verifying Organisation and Person models match their documentation.

DataSharing API was updated to design

---

.gitignore
Frontend/CO.CDP.OrganisationApp.Tests/CO.CDP.OrganisationApp.Tests.csproj
Frontend/CO.CDP.OrganisationApp.Tests/SessionTest.cs
Frontend/CO.CDP.OrganisationApp/ISession.cs
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/Session.cs
Frontend/CO.CDP.OrganisationApp/appsettings.json
GCGS-Central-Digital-Platform.sln

Introduced session in MVC App

---

Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs

GitHub has been reporting these on Pull Requests.

Remove unused variable warnings

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/ModelValidationHelper.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_ErrorSummary.cshtml

Model validation of details page

dp-49 - Model validation of details page, GDS Html Error Tags implantation

---

TestKit/CO.CDP.Testcontainers.PostgreSql.Tests/PostgreSqlFixtureTest.cs

Remove a blocking task operation from a test

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml.cs

Supplier provides organisation details

CDP-61 Supplier provides organisation details

---

.editorconfig

I also removed redundant js entries.

Enforce file-scoped namespaces

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/RequiredIfAttribute/RequiredIfAttributeTests.cs
Frontend/CO.CDP.OrganisationApp/CustomeValidationAttributes/RequiredIfAttribute.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs

#dp-11-refactored Organisations identification validation and tests

#dp-11-refactored Organisations identification validation and tests

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml.cs

Fixed the navigation for QA team. i.e. organisation details page was not navigating to organisation identification page.

#dp-11 organisation details page navigates to org identification page

---

.config/dotnet-tools.json
Makefile
README.md

https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool

Install dotnet-ef locally in the project

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Session.cs

DP-49: Supplier provides organisation's registered address

DP-49: Supplier provides organisation's registered address

---

Frontend/CO.CDP.OrganisationApp/CustomeValidationAttributes/RequiredIfAttribute.cs

#DP-11 On validation errors, highlighting the empty fields fixed

#DP-11 On validation errors, highlighting the empty fields fixed

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml

#DP-11 back button should always go to previous screen fixed

#DP-11 back button should always go to previous screen fixed

---

docs/decisions/0003-applying-database-migrations.adoc
docs/decisions/index.adoc

Best viewed when rendered by GitHub: https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/blob/bc80a0b5e9a140e366d284b013e9b9c0faa06f23/docs/decisions/0003-applying-database-migrations.adoc

Choose the database migration strategy

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs

Organisation summury list.  Populate your detail page from session.

Organisation summury list.  Populate your detail page from session.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs

Phone number not required on Organisation details registration

Phone number not required on Organisation details registration & added tenant email on summary screen

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs

Changes on Organisation Identification screen.
Removed Organisation Type from Organisation Details page.
Tenant mail id is not required in the summary page

Changes on Organisation Identification screen.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs

From the check your answers page, the Supplier can jump to the selected step to alter their details.
Once details are altered “Continue” takes the user back to the “Check your questions” page.
The “Back” link takes the user back to the “CHeck your questions” page

DP-45 - Supplier refines their details From the check your answers page, the Supplier can jump to the selected step to alter their details.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs

Remove personal details page email address

Remove personal details page email address

---

Dockerfile
Frontend/CO.CDP.OrganisationApp.Tests/CO.CDP.OrganisationApp.Tests.csproj
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
GCGS-Central-Digital-Platform.sln
Libraries/CO.CDP.Organisation.WebApiClient.Tests/CO.CDP.Organisation.WebApiClient.Tests.csproj
Libraries/CO.CDP.Organisation.WebApiClient.Tests/OrganisationClientIntegrationTest.cs
Libraries/CO.CDP.Organisation.WebApiClient/CO.CDP.Organisation.WebApiClient.csproj
Libraries/CO.CDP.Tenant.WebApiClient.Tests/CO.CDP.Tenant.WebApiClient.Tests.csproj
Services/CO.CDP.DataSharing.WebApi.Tests/CO.CDP.DataSharing.WebApi.Tests.csproj
Services/CO.CDP.Forms.WebApi.Tests/CO.CDP.Forms.WebApi.Tests.csproj
Services/CO.CDP.Organisation.Persistence.Tests/CO.CDP.Organisation.Persistence.Tests.csproj
Services/CO.CDP.Organisation.Persistence/CO.CDP.Organisation.Persistence.csproj
Services/CO.CDP.Organisation.WebApi.Tests/CO.CDP.Organisation.WebApi.Tests.csproj
Services/CO.CDP.Organisation.WebApi/CO.CDP.Organisation.WebApi.csproj
Services/CO.CDP.Organisation.WebApi/Properties/launchSettings.json
Services/CO.CDP.Organisation.WebApi/appsettings.Development.json
Services/CO.CDP.Person.WebApi.Tests/CO.CDP.Person.WebApi.Tests.csproj
Services/CO.CDP.Tenant.Persistence.Tests/CO.CDP.Tenant.Persistence.Tests.csproj
Services/CO.CDP.Tenant.WebApi.Tests/CO.CDP.Tenant.WebApi.Tests.csproj
Services/CO.CDP.Tenant.WebApi/CO.CDP.Tenant.WebApi.csproj
Services/CO.CDP.Tenant.WebApi/appsettings.Development.json
TestKit/CO.CDP.Testcontainers.PostgreSql.Tests/CO.CDP.Testcontainers.PostgreSql.Tests.csproj

#dp-66 organisation web api client

#dp-66 organisation web api client

---

GCGS-Central-Digital-Platform.sln

Person web api client dependendecy fix in solution

Person web api client dependendecy fix in solution

---

Libraries/CO.CDP.Person.WebApiClient.Tests/CO.CDP.Person.WebApiClient.Tests.csproj
Libraries/CO.CDP.Person.WebApiClient.Tests/PersonClientIntegrationTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabasePersonRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IPersonRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240502151351_AlterPerson.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240502151351_AlterPerson.cs
Services/CO.CDP.OrganisationInformation.Persistence/Person.cs
Services/CO.CDP.Person.WebApi.Tests/Api/RegisterPersonTest.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/RegisterPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Person.WebApi/Model/Command.cs
Services/CO.CDP.Person.WebApi/Model/Person.cs
Services/CO.CDP.Person.WebApi/appsettings.Development.json

DP-64 Person API refactor

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp/CO.CDP.OrganisationApp.csproj
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationAccount.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationAccount.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/appsettings.Development.json
Frontend/CO.CDP.OrganisationApp/appsettings.json

Organisation register happy path

Organisation register happy path

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/CO.CDP.OrganisationApp.csproj
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/appsettings.Development.json
Frontend/CO.CDP.OrganisationApp/appsettings.json

Supplier completes the registration - person is registered - happy path

DP-70 => Supplier completes the registration - person is registered - happy path

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs

Register organisation failure handling

Register organisation failure handling

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabasePersonRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IPersonRepository.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/GetPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/LookupPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Person.WebApi/Program.cs
Services/CO.CDP.Person.WebApi/UseCase/GetPersonUseCase.cs
Services/CO.CDP.Person.WebApi/UseCase/LookupPersonUseCase.cs
Services/CO.CDP.Tenant.WebApi/Program.cs

Supplier completes the registration - person is registered - failure handling

DP-73 Supplier completes the registration - person is registered - failure handling

---

Frontend/CO.CDP.OrganisationApp/Pages/Index.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Frontend/CO.CDP.OrganisationApp/wwwroot/css/site.css

Landing page refactor

---

Frontend/CO.CDP.OrganisationApp/OidcEvents.cs
Frontend/CO.CDP.OrganisationApp/Pages/Index.cshtml

One login error handling

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/PrivacyPolicyTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyNotice.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyNotice.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyPolicy.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyPolicy.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml

DP-110 Registration - Privacy Policy

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Libraries/CO.CDP.Person.WebApiClient.Tests/PersonClientIntegrationTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240509085219_RemovePersonAge.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240509085219_RemovePersonAge.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240509092447_AddUserPrincipalToPerson.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240509092447_AddUserPrincipalToPerson.cs
Services/CO.CDP.OrganisationInformation.Persistence/Person.cs
Services/CO.CDP.Person.WebApi.Tests/Api/RegisterPersonTest.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/GetPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/LookupPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/RegisterPersonUseCaseTest.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Person.WebApi/Model/Command.cs
Services/CO.CDP.Person.WebApi/Model/Person.cs

- Cleanup
- Register the tenant with the person

DP-65 Introduce UserPrincipal in the Person

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs

Person registration

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

Populate person details

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseTenantRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.Person.WebApi.Tests/UseCase/RegisterPersonUseCaseTest.cs

These are shared between repository tests.

Extract EntityFactory methods

---

.config/dotnet-tools.json
Libraries/CO.CDP.Organisation.WebApiClient/CO.CDP.Organisation.WebApiClient.csproj
Libraries/CO.CDP.Person.WebApiClient/CO.CDP.Person.WebApiClient.csproj
Libraries/CO.CDP.Tenant.WebApiClient/CO.CDP.Tenant.WebApiClient.csproj
Services/CO.CDP.Organisation.WebApi.Tests/CO.CDP.Organisation.WebApi.Tests.csproj
Services/CO.CDP.OrganisationInformation.Persistence/CO.CDP.OrganisationInformation.Persistence.csproj
Services/CO.CDP.Person.WebApi.Tests/CO.CDP.Person.WebApi.Tests.csproj
Services/CO.CDP.Tenant.WebApi.Tests/CO.CDP.Tenant.WebApi.Tests.csproj
TestKit/CO.CDP.Testcontainers.PostgreSql.Tests/CO.CDP.Testcontainers.PostgreSql.Tests.csproj

Warning NU1903 : Package 'Npgsql' 8.0.2 has a known high severity vulnerability, https://github.com/advisories/GHSA-x9vc-6hfv-hg8c

Update Npgsql (8.0.2 -> 8.0.4)

---

Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabasePersonRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240513143904_AddPersonOrganisationAssociation.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240513143904_AddPersonOrganisationAssociation.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationPerson.cs
Services/CO.CDP.OrganisationInformation.Persistence/Person.cs
Services/CO.CDP.Person.WebApi/AutoMapper/WebApiToPersistenceProfile.cs

Entity Framework to define relationships between persons and organisations

DP-65 Person is associated with the organisation

---

Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/UseCase/RegisterOrganisationUseCase.cs

API command to persist relationships between persons and organisations when creating a new organisation.
Organisation Management API: POST /organisations

DP-65 Person is associated with the organisation (api command)

---

Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/GetOrganisationsUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IOrganisationRepository.cs

List organisation by use urn

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationEmailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationNameModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationTypeTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationEmail.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationEmail.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml.cs

Registration - Enter Organisation Details

DP-117 - Registration - Enter Organisation Details

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationIdentificationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationNameModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationTypeTest.cs
Frontend/CO.CDP.OrganisationApp/ISession.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml.cs

#dp-115 Registration - Companies House Number YES scenario added

#dp-115 Registration - Companies House Number YES scenario added

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationSelectionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationSelection.cshtml.cs

Registered Organisation list
Fix broken flow

Registered Organisation list Fix broken flow

---

Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/LookupOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240517085304_OrganisationIdentifier.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240517085304_OrganisationIdentifier.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs

Organisation identifiers reconciliation

Organisation identifiers reconciliation

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Constants/OrganisationSchemeType.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationOverview.cshtml

Registration - Display Organisation scheme description on overview screen

DP-135 - Registration - Display Organisation scheme description on overview screen

---

Frontend/CO.CDP.OrganisationApp/Program.cs

This is also required by the load-balancer's target group

DP-1 Add basic health prob to organisation-app

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/ErrorPageTests.cs
Frontend/CO.CDP.OrganisationApp/ExceptionMiddleware.cs
Frontend/CO.CDP.OrganisationApp/Pages/Error.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Error.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
GCGS-Central-Digital-Platform.sln

Feature/dp 130 consistent error handling in UI

Feature/dp 130 consistent error handling in UI

---

Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareReceipt.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareRequest.cs

Add examples for POST share/data

---

Libraries/CO.CDP.Swashbuckle.Tests/Security/SecurityExtensionsTest.cs
Libraries/CO.CDP.Swashbuckle/Security/SecurityExtensions.cs
Makefile
README.md
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/CO.CDP.DataSharing.WebApi.csproj
Services/CO.CDP.DataSharing.WebApi/Program.cs
Services/CO.CDP.DataSharing.WebApi/appsettings.json

Reconfigure security for datasharing to use the Bearer token

---

Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/Model/Form.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareReceipt.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareVerificationReceipt.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareVerificationRequest.cs

Add shared data operation stub

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/YourDetails.cshtml.cs

Re https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/129

Fix the problem with failed user registration

---

Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Services/CO.CDP.OrganisationInformation/ContactPoint.cs
Services/CO.CDP.OrganisationInformation/Identifier.cs

re https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/134
I made too many fields non-nullable.

Fix organisation registration

---

Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/Model/ShareVerificationReceipt.cs

DP-138: Update the share code verification response to indicate if the share code is the latest one

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/ErrorPageTests.cs
Frontend/CO.CDP.OrganisationApp/ExceptionMiddleware.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Libraries/CO.CDP.Common/Enums/AddressType.cs
Libraries/CO.CDP.Organisation.WebApiClient.Tests/OrganisationClientIntegrationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/LookupOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/Address.cs
Services/CO.CDP.OrganisationInformation.Persistence/CO.CDP.OrganisationInformation.Persistence.csproj
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240528141244_Address.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240528141244_Address.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
Services/CO.CDP.OrganisationInformation/Address.cs

Allow multiple address for Organisation

Allow multiple address for Organisation

---

Services/CO.CDP.DataSharing.WebApi/Model/OrganisationReference.cs
Services/CO.CDP.DataSharing.WebApi/Model/SupplierInformation.cs

Fix the organisation (party) role examples

---

terragrunt/components/core/iam/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/core-iam/s3-datasource.tf
terragrunt/modules/core-iam/variables.tf

- Remove hard-coded tfstate bucket names
- Tidy up some common configurations

DP-1 Grant Kuba permission to assume terraform role

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationSelection.cshtml

DP-169 - Observation: Supplier registration flow is not aligned with the Prototype v4

Observation: Supplier registration flow is not aligned with the Prototype v4

---

terragrunt/components/service/telemetry/terragrunt.hcl
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/telemetry/cloudwatch.tf
terragrunt/modules/telemetry/datasource.tf
terragrunt/modules/telemetry/locals.tf
terragrunt/modules/telemetry/templates/dashboard-service-deployment.json.tftpl
terragrunt/modules/telemetry/variables.tf

Add telemetry component, begin with deployer functions observability.

DP-1 Draft Deployment dashboard

---

Services/CO.CDP.Forms.WebApi/Api/Forms.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs
Services/CO.CDP.Tenant.WebApi/Program.cs

In preparation to shareing the OpenAPI contract.

Remove stubs for endpoints that are unlikely to be needed

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/BuyerSelectDevolvedRegulationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Constants/AddressType.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerOrganisationType.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerSelectDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml.cs
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/LookupOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs
Services/CO.CDP.OrganisationInformation/Address.cs
Services/CO.CDP.OrganisationInformation/AddressType.cs

Address type refactor

---

terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/core-networking/outputs.tf
terragrunt/modules/core-networking/route53.tf
terragrunt/modules/ecs/route53.tf
terragrunt/modules/ecs/variables.tf

- Create subdomains for all services

DP-1 Add pre-prods public hosted zones

---

Services/CO.CDP.OrganisationInformation/OrganisationReference.cs
Services/CO.CDP.Tenant.WebApi.Tests/Api/TenantLookupTest.cs
Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs
Services/CO.CDP.Tenant.WebApi/CO.CDP.Tenant.WebApi.csproj
Services/CO.CDP.Tenant.WebApi/Model/TenantLookup.cs

DP-128 tenant lookup stub

---

terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/modules/api-gateway/cloudwatch.tf
terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/api-gateway/main.tf
terragrunt/modules/api-gateway/outputs.tf
terragrunt/modules/api-gateway/variables.tf
terragrunt/modules/core-iam/api-gateway-datasource.tf
terragrunt/modules/core-iam/api-gateway.tf
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/core-iam/ci.tf
terragrunt/modules/core-iam/outputs.tf
terragrunt/modules/database/cloudwatch.tf
terragrunt/modules/ecs/cloudwatch.tf
terragrunt/modules/ecs/outputs.tf

- Split Terraform's IAM policy

DP-1 Add API Gateway

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/BuyerDevolvedRegulationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/BuyerOrganisationTypeTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/BuyerSelectDevolvedRegulationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/RegistrationStepModelTest.cs
Frontend/CO.CDP.OrganisationApp/Constants/ErrorMessagesList.cs
Frontend/CO.CDP.OrganisationApp/Models/RegistrationDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerDevolvedRegulation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerOrganisationType.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerOrganisationType.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerSelectDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerSelectDevolvedRegulation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationEmail.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNonUKAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/RegistrationStepModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/_ViewImports.cshtml

Session handling buyer registration

Session handling buyer registration

---

Prototype/CompanyHouseApi.Integration/ExternalServices/CompaniesHouse/CompaniesHouseService.cs
Prototype/CompanyHouseApi.Integration/ExternalServices/CompaniesHouse/ICompaniesHouseService.cs
Prototype/CompanyHouseApi.Integration/ExternalServices/CompaniesHouse/PersonsWithSignificantControl.cs
Prototype/CompanyHouseApi.Integration/Pages/Index.cshtml
Prototype/CompanyHouseApi.Integration/Pages/Index.cshtml.cs
docs/external/index.adoc

Added new endpoint for Persons with-significant-control

#dp-139 get list of people with-significant-control has been added

---

Services/CO.CDP.Organisation.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Organisation.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.Person.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Person.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.Tenant.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Tenant.WebApi/Extensions/ServiceCollectionExtensions.cs
TestKit/CO.CDP.TestKit.Mvc.Tests/LoggingExtensionsTest.cs

DP-129 Observation - validation message is not user friendly message

---

terragrunt/README.md
terragrunt/modules/ecs/security-groups.tf
terragrunt/secrets/.gitignore

[DP-1](https://noticingsystem.atlassian.net/browse/DP-1) 
- Update OneLogin credentials 
- Allow outbound traffic over HTTPS

DP-1 Update OneLogin

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/PrivacyPolicyTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/RegistrationStepModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/YourDetailsModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/AuthorisedSessionAttribute.cs
Frontend/CO.CDP.OrganisationApp/Pages/LoggedInUserAwareModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyPolicy.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerDevolvedRegulation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerOrganisationType.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/BuyerSelectDevolvedRegulation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationEmail.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNonUKAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationOverview.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/RegistrationStepModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/YourDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/YourDetails.cshtml.cs

Application wide session expiry handling

Application wide session expiry handling

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OrganisationOverviewTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs

Moved organisation summary outside registration

Moved organisation summary outside registration

---

terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/api-gateway/main.tf
terragrunt/modules/api-gateway/variables.tf
terragrunt/modules/ecs-service/listeners.tf
terragrunt/modules/ecs-service/security-groups.tf
terragrunt/modules/ecs-service/variables.tf
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-data-sharing.tf
terragrunt/modules/ecs/service-forms.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/ecs/service-person.tf
terragrunt/modules/ecs/service-tenant.tf
terragrunt/modules/ecs/step-function.tf
terragrunt/modules/ecs/task-organisation-information-migrations.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-information-migrations.json.tftpl
terragrunt/modules/ecs/variables.tf

[DP-1](https://noticingsystem.atlassian.net/browse/DP-1) 
- Centralise service configurations
- Use it for both `api-gateway` and `ecs` modules
- Simplify service/task definitions

DP-1 Centralise service configurations

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs

restored check on updatedOn date

restored check on updatedOn date

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Constants/DevolvedRegulation.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Libraries/CO.CDP.Organisation.WebApiClient.Tests/OrganisationClientIntegrationTest.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation/BuyerInformation.cs

DP-173 - Registration - Buyer Route - Buyer Submission Page

Registration - Buyer Route - Buyer Submission Page

---

compose.yml

DB migration fix

---

terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/modules/api-gateway/acm.tf
terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/api-gateway/main.tf
terragrunt/modules/api-gateway/route53.tf
terragrunt/modules/api-gateway/variables.tf
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/core-networking/route53.tf
terragrunt/modules/ecs/outputs.tf

- Link up integrations to service domains
- Add custom domain and its certificate in N.Virginia

DP-1 Update API Gateway

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OrganisationOverviewTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/PageNotFound.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetSupplierInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/Properties/launchSettings.json
Services/CO.CDP.Organisation.WebApi/UseCase/GetSupplierInformationUseCase.cs

Supplier Information - Organisation

Supplier Information - Organisation

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierBasicInformationTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateBuyerInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Properties/launchSettings.json

Organisation - Supplier - Basic Information

Organisation - Supplier - Basic Information

---

Frontend/CO.CDP.OrganisationApp/Pages/OrganisationOverview.cshtml

Supplier information link visibility

Supplier information link visibility

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierBasicInformationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/SupplierInformationTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240612141027_AlterSupplierInformationRenameCompletedOrganisationType.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240612141027_AlterSupplierInformationRenameCompletedOrganisationType.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs

Change column name for SupplierInformation table
CompletedOrganisationType => CompletedOperationType

Change column name for SupplierInformation table CompletedOrganisationType => CompletedOperationType

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierBasicInformationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVat.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVat.cshtml.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateBuyerInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateSupplierInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Model/Exceptions.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/GetSupplierInformationUseCase.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateBuyerInformationUseCase.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateOrganisationUseCase.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateSupplierInformationUseCase.cs

Supplier information VAT question

Supplier information VAT question

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNonUKAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml.cs

Address optional field bug fix

Address optional field bug fix

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegisteredAddress.cshtml

International address back link bug

International address back link bug

---

terragrunt/components/service/telemetry/terragrunt.hcl
terragrunt/modules/telemetry/cloudwatch.tf
terragrunt/modules/telemetry/locals.tf
terragrunt/modules/telemetry/templates/dashboard-logs-warn-err.json.tftpl
terragrunt/modules/telemetry/variables.tf

While waiting for OneLogin add ...

DP-1 Add dashboard for all services warning and error logs

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationDetailsSummaryModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs

Reduces noise at the call site by removing irrelevant details.

Extract extension methods for web api client calls

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierDetailsFactory.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierEmailAddressTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierWebsiteModelQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateSupplierInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateSupplierInformationUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240617190841_TradeAssurance.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240617190841_TradeAssurance.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs

Added update support for Trade assurance and LegalForm

Make Trade Assurance and qualification fields required Added update support for Trade assurance and LegalForm

---

Services/CO.CDP.Organisation.WebApi.Tests/Api/RegisterOrganisationTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/DeleteSupplierInformationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/DeleteSupplierInformationUseCase.cs

Delete supplier information

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierBasicInformationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierDetailsFactory.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceAwardedDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceBody.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceCheckAnswerTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceReferenceNumberTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceRemoveConfirmationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceSummaryTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/TempDataServiceTest.cs
Frontend/CO.CDP.OrganisationApp/ITempDataService.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceAwardedDate.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceAwardedDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceBody.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceBody.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceCheckAnswer.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceCheckAnswer.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceReferenceNumber.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceReferenceNumber.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceRemoveConfirmation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceRemoveConfirmation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/TempDataService.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs

Supplier Trade Assurance

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormCaQuestionModelTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormFormationDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormLawRegisteredModelTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormOtherOrganisationModelTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormSelectOrganisationModelTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierDetailsFactory.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/TradeAssuranceAwardedDateTest.cs
Frontend/CO.CDP.OrganisationApp/Constants/RegExPatterns.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormCaQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormCaQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormFormationDate.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormFormationDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormLawRegistered.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormLawRegistered.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormOtherOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormOtherOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormSelectOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormSelectOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/TradeAssuranceAwardedDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240621213825_AlterLegalFormChangeDataType.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240621213825_AlterLegalFormChangeDataType.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs

Basic Information - Organisation - Legal form

DP-155 - Basic Information - Organisation - Legal form

---

Makefile
terragrunt/README.md
terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/core-networking/outputs.tf
terragrunt/modules/database/secret-manager.tf
terragrunt/modules/ecs-service/listeners.tf
terragrunt/modules/ecs/datasource.tf
terragrunt/modules/ecs/service-authority.tf
terragrunt/modules/ecs/service-data-sharing.tf
terragrunt/modules/ecs/service-forms.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/ecs/service-person.tf
terragrunt/modules/ecs/service-tenant.tf
terragrunt/modules/ecs/task-organisation-information-migrations.tf
terragrunt/modules/ecs/templates/task-definitions/authority.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/data-sharing.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/forms.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation-information-migrations.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/person.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/tenant.json.tftpl
terragrunt/modules/ecs/variables.tf

These changes have been rolled out in [development](https://dev.supplier.information.findatender.codatt.net/), [staging](https://staging.supplier.information.findatender.codatt.net/) and [integration](https://integration.supplier.information.findatender.codatt.net/) accounts

DP-1 (DP-195) Correct OneLogin redirect_url & and authority service 

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierBasicInformationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierDetailsFactory.cs
Frontend/CO.CDP.OrganisationApp/Constants/OperationTypes.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierOperationQuestion.cshtml

DP-154 basic information web

---

terragrunt/tools/grafana/Dockerfile
terragrunt/tools/grafana/README.md
terragrunt/tools/grafana/configs/dashboard.yaml
terragrunt/tools/grafana/configs/dashboards/application/logs-authority.json
terragrunt/tools/grafana/configs/dashboards/application/logs-critical.json
terragrunt/tools/grafana/configs/dashboards/application/logs-data-sharing.json
terragrunt/tools/grafana/configs/dashboards/application/logs-forms.json
terragrunt/tools/grafana/configs/dashboards/application/logs-grafana.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-app.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-information-migrations.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation.json
terragrunt/tools/grafana/configs/dashboards/application/logs-person.json
terragrunt/tools/grafana/configs/dashboards/application/logs-tenant.json
terragrunt/tools/grafana/configs/dashboards/infrastructure/ecs.json
terragrunt/tools/grafana/configs/datasource.yaml.tpl
terragrunt/tools/grafana/configs/entrypoint.sh

This is to replace https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/222

DP-217 Grafana image

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormCompanyActQuestionModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormCompanyActQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormCompanyActQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormOtherOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormSelectOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml

DP-155 
Bug fix and renaming forms and model

Bug fix and renaming forms and model

---

terragrunt/tools/grafana/configs/dashboards/application/logs-authority.json
terragrunt/tools/grafana/configs/dashboards/application/logs-data-sharing.json
terragrunt/tools/grafana/configs/dashboards/application/logs-forms.json
terragrunt/tools/grafana/configs/dashboards/application/logs-grafana.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-app.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-information-migrations.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation.json
terragrunt/tools/grafana/configs/dashboards/application/logs-person.json
terragrunt/tools/grafana/configs/dashboards/application/logs-tenant.json

Ideally we need to have a convention on logging format and log level but for now this will improve the dashboards a touch

BAU expand error and warning panel's query to pick on more relevant keywords

---

Frontend/CO.CDP.OrganisationApp/OidcEvents.cs
Frontend/CO.CDP.OrganisationApp/Pages/Index.cshtml

Generic one-login error display

Generic one-login error display

---

Libraries/CO.CDP.Swashbuckle.Tests/Filter/ProblemDetailsOperationFilterTest.cs
Libraries/CO.CDP.Swashbuckle/Filter/ProblemDetailsOperationFilter.cs
Services/CO.CDP.Organisation.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.Person.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Person.WebApi/Api/Person.cs
Services/CO.CDP.Person.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.Tenant.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.Tenant.WebApi/Api/Tenant.cs
Services/CO.CDP.Tenant.WebApi/Extensions/ServiceCollectionExtensions.cs

POC of an alternative approach  to https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/244/ that hopefully results in less maintenance.

DP-186: Document error responses

---

terragrunt/modules/database/rds.tf
terragrunt/modules/ecs/templates/task-definitions/forms.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/person.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/tenant.json.tftpl

DP-209 Hardcode CDP API Key

---

Services/CO.CDP.Organisation.Authority/appsettings.Development.json

Otherwise, the service will not work out of the box in the IDE

Bring back localhost as the issuer default

---

Makefile
docs/development/01-development-environment.adoc

Authority Api Doc update

---

Dockerfile
GCGS-Central-Digital-Platform.sln
Makefile
Services/CO.CDP.EntityVerification.Tests/CO.CDP.EntityVerification.Tests.csproj
Services/CO.CDP.EntityVerification.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.EntityVerification/Api/PponEndpointExtensions.cs
Services/CO.CDP.EntityVerification/CO.CDP.EntityVerification.csproj
Services/CO.CDP.EntityVerification/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.EntityVerification/Program.cs
Services/CO.CDP.EntityVerification/Properties/launchSettings.json
Services/CO.CDP.EntityVerification/appsettings.Development.json
Services/CO.CDP.EntityVerification/appsettings.json
compose.common.yml
compose.yml
docker/gateway/templates/01-gateway.conf.template

Once this is merged, everyone will need to add entity-verification to their compose.override.yml:
```
entity-verification:
environment:
ASPNETCORE_ENVIRONMENT: Development
deploy:
replicas: 1
```

Bootstrap the EntityVerification project

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierDetailsFactory.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierEmailAddressTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierWebsiteModelQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs

Changes on SupplierInformation summary page to reflect Connected person

Changes on SupplierInformation summary page to reflect Connected person

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierInformationSummaryTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateSupplierInformationUseCase.cs

DP-251 - Connected Person Declaration form

DP-251 - Connected Person Declaration form

---

Frontend/CO.CDP.OrganisationApp/Program.cs
Services/CO.CDP.Forms.WebApi/Properties/launchSettings.json
compose.yml

Forms api docker reference fix

Forms api docker reference fix

---

terragrunt/modules/database/templates/state-machine/update-connection-string.json.tftpl

- We do not expect a JSON value here

BAU Keep only the connection string's value

---

Services/CO.CDP.EntityVerification.Tests/Events/EventDeserializerTest.cs
Services/CO.CDP.EntityVerification.Tests/Ppon/OrganisationRegisteredEventHandlerTests.cs
Services/CO.CDP.EntityVerification/CO.CDP.EntityVerification.csproj
Services/CO.CDP.EntityVerification/Events/Events.cs
Services/CO.CDP.EntityVerification/Events/Values.cs

The organisation service will publish full organisation details, but EV will only read details it's interested in.

Include identifiers in the OrganisationRegistered event

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterNameTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegistrationDateTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegistrationDate.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegistrationDate.cshtml.cs

DP-306 - Connected Persons - Organisation - Registered Date of Connected persons
DP-307 - Connected Persons - Organisation - Declared Register

DP-306 - Connected Persons - Organisation - Registered Date of Connected persons DP-307 - Connected Persons - Organisation - Declared Register

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml
Libraries/CO.CDP.AwsServices.Tests/AwsFileManagerTest.cs
Libraries/CO.CDP.AwsServices.Tests/CO.CDP.AwsServices.Tests.csproj
Libraries/CO.CDP.AwsServices.Tests/LocalStackFixture.cs

AmazonS3Client unit test using LocalStackContainer

AmazonS3Client unit test using LocalStackContainer

---

terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/modules/api-gateway/api-root.tf
terragrunt/modules/api-gateway/datasource.tf
terragrunt/modules/api-gateway/iam.tf
terragrunt/modules/api-gateway/main.tf
terragrunt/modules/api-gateway/step-function.tf
terragrunt/modules/api-gateway/templates/state-machine/api-gateway-deployment.json.tftpl
terragrunt/modules/api-gateway/variables.tf
terragrunt/modules/core-iam/api-gateway.tf
terragrunt/modules/core-iam/outputs.tf

- Make the API Gateway deployment module more robust

DP-190 Provision step-function deploy api-gateway's latest stage

---

terragrunt/components/orchestrator/ci/terragrunt.hcl
terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/service/queue/terragrunt.hcl
terragrunt/modules/api-gateway/api-root.tf
terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/api-gateway/templates/landing-page.html.tftpl
terragrunt/modules/core-iam/terraform-datasource.tf
terragrunt/modules/ecs/s3.tf
terragrunt/modules/ecs/variables.tf
terragrunt/modules/kms/README.md
terragrunt/modules/kms/datasource.tf
terragrunt/modules/kms/main.tf
terragrunt/modules/kms/outputs.tf
terragrunt/modules/kms/templates/key-policy.json.tftpl
terragrunt/modules/kms/variables.tf
terragrunt/modules/orchestrator/ci/s3.tf
terragrunt/modules/orchestrator/ci/variables.tf
terragrunt/modules/orchestrator/iam/locals.tf
terragrunt/modules/queue/locals.tf
terragrunt/modules/queue/main.tf
terragrunt/modules/queue/outputs.tf
terragrunt/modules/queue/variables.tf
terragrunt/modules/s3-bucket/datasource.tf
terragrunt/modules/s3-bucket/kms.tf
terragrunt/modules/s3-bucket/main.tf
terragrunt/modules/s3-bucket/variables.tf

The delay in approving and merging [DP-397](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/328) and [DP-311](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/333) is the reason I have raised this pull request, which contains changes from both branches.
This PR creates SQS queues and S3 buckets for services. not linked to any service yet though.

DP-397 & DP-311

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegistrationDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityControlConditionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLawRegisterTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegistrationDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityControlCondition.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLawRegister.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOrganisationName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOrganisationName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityPostalSameAsRegisteredAddress.cshtml.cs

Fixed workflow for 
Organisation =>
Select category out of 5 categories and to => Check answer page

Fixed workflow for >Organisation >Select category out of 5 categories and to Check answer page

---

Frontend/CO.CDP.OrganisationApp/FormsEngine.cs
Frontend/CO.CDP.OrganisationApp/Models/DynamicForms.cs
Services/CO.CDP.Forms.WebApi.Tests/UseCase/GetFormSectionQuestionsUseCaseTest.cs
Services/CO.CDP.Forms.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Forms.WebApi/Model/FormAnswer.cs
Services/CO.CDP.Forms.WebApi/Model/FormAnswerSet.cs
Services/CO.CDP.Forms.WebApi/Model/FormQuestion.cs
Services/CO.CDP.Forms.WebApi/Model/SectionQuestionsResponse.cs
Services/CO.CDP.Forms.WebApi/Program.cs
Services/CO.CDP.Forms.WebApi/UseCase/GetFormSectionQuestionsUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseFormRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Forms/Form.cs
Services/CO.CDP.OrganisationInformation.Persistence/Forms/FormAnswer.cs

Defined AnswerSer Schema in GetQuestions Endpoint

Fix Nested NextQuestion Object Issue Defined AnswerSer Schema in GetQuestions Endpoint

---

Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240715160432_CreateFinancialInformationSeedDate.cs

Update seed data to align with the v5 prototype flow and remove all existing question types.

DP-313 Financial Information - Seed data (v5 prototype)

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidencyTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidency.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidency.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityPscDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityState.cs

DP-345 Connected Persons - Individual - Directory Residency

Connected Persons - Individual - Directory Residency

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240715160432_CreateFinancialInformationSeedDate.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240725142711_UpdateFinancialInfoSeedData.cs

Fix for validation - platform independent

Fix for validation - platform independent

---

Libraries/CO.CDP.MQ.Tests/CO.CDP.MQ.Tests.csproj
Libraries/CO.CDP.MQ.Tests/Hosting/DispatcherBackgroundServiceTest.cs
Libraries/CO.CDP.MQ/CO.CDP.MQ.csproj
Libraries/CO.CDP.MQ/Hosting/DispatcherBackgroundService.cs
Services/CO.CDP.EntityVerification/Program.cs

so it could be reused in the organisation service

Move Dispatcher Background Service to the MQ project 

---

Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240729120131_UpdateFormAnswerSectionSet.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240729120131_UpdateFormAnswerSectionSet.cs

Update foreign key relationship between FormAnswerSet and FormSection

EF Update Form Answer Section Set

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Model/Organisation.cs
Services/CO.CDP.OrganisationInformation.Persistence/ConnectedEntity.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240729170003_AlterConnectedEntitiesAddColumnResidentCountry.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240729170003_AlterConnectedEntitiesAddColumnResidentCountry.cs

Director residency - EF database migration to create new column in connected_individual_trust table

Director residency - EF database migration

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidencyTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityControlCondition.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidency.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidency.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityPscDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedPersonSummary.cshtml

Connected person - Individual - workflow link to check answer page
DP-338 - Connected Persons - Individual - Director Details
DP-341 - Connected Persons - Individual - Director Address
DP-349 - Connected Persons - Individual - Director Check your Answers

Connected person - Individual - workflow link to check answer page

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDate.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedPersonSummary.cshtml.cs

Insolvency date fixsolvency date fix

---

terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-authority.tf
terragrunt/modules/ecs/service-data-sharing.tf
terragrunt/modules/ecs/service-entity-verification.tf
terragrunt/modules/ecs/service-forms.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/ecs/service-person.tf
terragrunt/modules/ecs/service-tenant.tf
terragrunt/modules/ecs/task-migrations.tf

- ![image](https://github.com/user-attachments/assets/4f8100db-4aeb-40d4-a53d-f63cba05b637)
- ![image](https://github.com/user-attachments/assets/c3d68c5b-4da1-4959-abb9-2694e4a09bfc)
- ![image](https://github.com/user-attachments/assets/2945e082-3e81-4ad3-9e68-f7917cd4bc16)

DP-200 Revert overwriting the environmnet names

---

terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/core-iam/ci-datasource.tf
terragrunt/modules/ecs/datasource.tf
terragrunt/modules/orchestrator/ci/buildspecs/update-account.yml
terragrunt/modules/orchestrator/ci/buildspecs/update-ecs-services.yml
terragrunt/modules/orchestrator/ci/trigger_update_account.tf
terragrunt/modules/orchestrator/ci/trigger_update_ecs_services.tf
terragrunt/modules/queue/locals.tf
terragrunt/modules/tools/service-healthcheck.tf
terragrunt/tools/codebuild/Dockerfile
terragrunt/tools/codebuild/README.md

- Update the buildspecs
- Update all components if there are infra changes
- Include updating the orchestrator logic
- Link update account pipeline to the repo

DP-191 Enable Codestar in orchestrator

---

Libraries/CO.CDP.AwsServices.Tests/Sqs/SqsDispatcherTest.cs
Libraries/CO.CDP.AwsServices.Tests/Sqs/SqsPublisherTest.cs
Libraries/CO.CDP.AwsServices/Extensions.cs
Libraries/CO.CDP.AwsServices/Sqs/SqsDispatcher.cs
Libraries/CO.CDP.AwsServices/Sqs/SqsPublisher.cs
Services/CO.CDP.EntityVerification/appsettings.Development.json
Services/CO.CDP.Organisation.WebApi/appsettings.Development.json

```
info: CO.CDP.AwsServices.Sqs.SqsDispatcher[0]
Received 1 message(s)
dbug: CO.CDP.AwsServices.Sqs.SqsDispatcher[0]
Handling the message with MessageId=452370d1-5931-4d12-8de5-f55057689cfb
dbug: CO.CDP.AwsServices.Sqs.SqsDispatcher[0]
Found 1 subscribers to handle the `OrganisationRegistered` message
dbug: CO.CDP.AwsServices.Sqs.SqsDispatcher[0]
Handling the `OrganisationRegistered` message: `{"Name":"Acme", "Id": "0ccbfd3a-2f9d-4d8b-8d2e-1a976bdb990a", "Roles": [], "Identifier": {"Scheme": "GB-COH", "Id": "123123", "LegalName": "Acme", "Uri": null}, "AdditionalIdentifiers": []}`
dbug: CO.CDP.AwsServices.Sqs.SqsPublisher[0]
Publishing the `PponGenerated` message: `{"Id":"06a4e927a1004cdca0d4789cc7170c8a","Scheme":"CDP-PPON","LegalName":"Acme","OrganisationId":"0ccbfd3a-2f9d-4d8b-8d2e-1a9 …
```

Log messages being published and dispatched

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDate.cshtml.cs

workflow fix for taken over company

Check answer fix workflow fix for taken over company

---

compose.yml
terragrunt/modules/ecs/templates/task-definitions/authority.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/data-sharing.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/entity-verification.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/forms.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/person.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/tenant.json.tftpl

- Pass service's queue as the publisher for the same service 
- Add Version
- Tidy up env_vars

DP-408 Tidy up environment variables

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/DynamicFormsPageModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/Address.cs
Frontend/CO.CDP.OrganisationApp/Models/DynamicForms.cs
Frontend/CO.CDP.OrganisationApp/Models/FormQuestionViewModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementAddressModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAddAnotherAnswerSet.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/_FormElementAddress.cshtml

Forms Address UI work

---

Services/CO.CDP.DataSharing.WebApi/CO.CDP.DataSharing.WebApi.csproj
Services/CO.CDP.DataSharing.WebApi/Program.cs
Services/CO.CDP.DataSharing.WebApi/appsettings.Development.json
Services/CO.CDP.DataSharing.WebApi/appsettings.json

Data Sharing API Startup fix

---

Frontend/CO.CDP.OrganisationApp/FormsEngine.cs
Frontend/CO.CDP.OrganisationApp/Models/Address.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Forms/DynamicFormsPage.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAddAnotherAnswerSet.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAddAnotherAnswerSet.cshtml.cs
Services/CO.CDP.Forms.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Forms.WebApi/Model/FormAnswer.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseFormRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/Forms/FormAnswer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240806121658_FormAnswerAddressValue.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240806121658_FormAnswerAddressValue.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs

Address Value DB change

---

Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240802095312_CreateShareCodesSeedDate.cs

[DP-428](https://noticingsystem.atlassian.net/browse/DP-428)
Updated to add in missing screen

DP-428 BE- Share my information - Declaration form (Forms API) updated

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLawEnforceTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLawEnforce.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLawEnforce.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOrganisationCategory.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOrganisationCategory.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedPersonSummary.cshtml.cs

Law enforce

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseAuthenticationKeyRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/AuthenticationKey.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240809133920_AddUniqueIndexToApiKey.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240809133920_AddUniqueIndexToApiKey.cs

Adds a unique constraint to the `key`.

DP-455: Add an unique index constraint to the API Key

---

Services/CO.CDP.Forms.WebApi/Program.cs

Missed it somehow earlier :see_no_evil:

DP-200: Make forms respect the SwaggerUI feature flag setting

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDate.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDate.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityControlCondition.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOverseasCompanyQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOverseasCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityPostalSameAsRegisteredAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRemoveConfirmation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityState.cs

DP-371, DP-372, DP-373, DP-374, DP-375, DP-468

Connected person - No Journey

---

Services/CO.CDP.EntityVerification.Tests/Ppon/OrganisationUpdatedSubscriberTests.cs
Services/CO.CDP.EntityVerification/Ppon/OrganisationUpdatedSubscriber.cs

[DP-467](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-467)

No longer inserts PPON identifier on OrganisationUpdated.

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/outputs.tf
terragrunt/modules/ecs/service-authority.tf
terragrunt/modules/ecs/service-data-sharing.tf
terragrunt/modules/ecs/service-entity-verification.tf
terragrunt/modules/ecs/service-forms.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/ecs/service-person.tf
terragrunt/modules/ecs/service-tenant.tf
terragrunt/modules/ecs/task-migrations.tf
terragrunt/modules/ecs/variables.tf

This is our first attempt to pin services in one of our accounts to specific version.
It has been provisioned in integration and seems promising, but needs more testing when goes through the pipeline once its been merged.

DP-492 POC pinning services to specific version in different accounts

---

terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl

BAU Add link to view published revision

---

terragrunt/README.md

DP-494 Document pining process

---

Services/CO.CDP.DataSharing.WebApi.Tests/AutoMapper/AutoMapperFixture.cs
Services/CO.CDP.DataSharing.WebApi.Tests/AutoMapper/DataSharingProfileTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/EntityFactory.cs
Services/CO.CDP.DataSharing.WebApi.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/ShareCodeExtensionsTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GenerateShareCodeUseCaseTest.cs
Services/CO.CDP.Forms.WebApi.Tests/UseCase/UpdateFormSectionAnswersUseCaseTest.cs
Services/CO.CDP.Forms.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Forms.WebApi/Model/SharedConsent.cs
Services/CO.CDP.Forms.WebApi/UseCase/UpdateFormSectionAnswersUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseFormRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseFormRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Forms/FormAnswer.cs
Services/CO.CDP.OrganisationInformation.Persistence/IFormRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240807073912_MoveOrganisationToSharedConsent.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240807073912_MoveOrganisationToSharedConsent.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240814081657_TweakSharedConsentEntity.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240814081657_TweakSharedConsentEntity.cs

[DP-442](https://noticingsystem.atlassian.net/browse/DP-442)
Extending the Forms API to support new question types and tightly coupling SharedConsent with AnswerSets.

DP-442 BE- Share my information - Answering Declaration form (Forms API)

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterNameTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntitySelectTypeTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedPersonSummaryTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedPersonSummary.cshtml.cs

Register name bug fix
Session improvment

Register name bug fix & Session improvment

---

Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Frontend/CO.CDP.OrganisationApp/appsettings.AwsDevelopment.json
Frontend/CO.CDP.OrganisationApp/appsettings.AwsIntegration.json
Frontend/CO.CDP.OrganisationApp/appsettings.AwsProduction.json
Frontend/CO.CDP.OrganisationApp/appsettings.AwsStaging.json
Frontend/CO.CDP.OrganisationApp/appsettings.Development.json
Frontend/CO.CDP.OrganisationApp/appsettings.json

Add Google Tag to SIRSI

---

Services/CO.CDP.EntityVerification.Tests/UseCase/LookupIdentifierUseCaseTest.cs
Services/CO.CDP.EntityVerification/UseCase/LookupIdentifierUseCase.cs

[DP-390](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-390)

Bug fix: PPON Lookup not returning PPON in list of identifiers.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrustTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyInsolvencyDateTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityControlConditionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLawEnforceTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLawRegisterTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityOverseasCompanyQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityControlCondition.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLawRegister.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestion.cshtml.cs

bug fix more unit test

---

docs/development/decisions/0006-acceptance-tests.adoc
docs/development/decisions/index.adoc

To view the document rendered, see [0006-acceptance-tests.adoc](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/blob/acceptance-tests/docs/development/decisions/0006-acceptance-tests.adoc).

Draft the decision to start writing acceptance tests

---

compose.yml

#dp-271 share code compose.yml updated for docker
This will fix the issues for QA

#dp-271 share code compose.yml updated for docker

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersCommon.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityOverseasCompanyQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRegistrationDateQuestion.cshtml.cs

Connected Persons - Individual - COMPANIES HOUSE "NO" PATH - Organisation - Check your Answers enhancements

DP-519 Connected Persons - Check your Answers enhancements

---

.github/workflows/build.yml
compose.yml

Added EntityVerificationService port to organisation app.

Added EntityVerificationService port to organisation app.

---

.mise.toml
terragrunt/providers.tf
terragrunt/tools/codebuild/README.md

New versions have been tested locally.
New Codebuild image with the expected version has been built and published to orchestrator's ECR

DP-530 Upgrade tools and provider

---

Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20240823123421_CountryCode.Designer.cs

Migration merge fix

---

terragrunt/components/terragrunt.hcl

This will be a neutral merge, as the introduced changes have already been applied to the integration account.

DP-534 Pin version 0.3.0 in integration

---

terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl

Sync with dc9a2d7c compose changes

DP-392 Sync org-app configuration with latest local changes

---

terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/modules/api-gateway/api-root.tf
terragrunt/modules/api-gateway/variables.tf

DP-534 Concider potential pinned version in API landing page

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationAlreadyRegistered.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegistrationUnavailable.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs

[DP-393](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-393)

PPON Service - Lookup While adding VAT in supplier information

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersCommon.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml.cs

Legal forms are not getting displayed in summary screen of organisation>Equivalent to register company incompany house no path

DP-561 Connected person fix

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationRegistrationUnavailable.cshtml

[DP-523](https://noticingsystem.atlassian.net/browse/DP-523#icft=DP-523)

DP-523 PPON service not available

---

terragrunt/README.md
terragrunt/modules/ecs/datasource.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl

- Pass the secret to organisation-app service via FtsService environment variable
- Update documentation

DP-444 Add secrets for FTS Service URL

---

Services/CO.CDP.EntityVerification/CO.CDP.EntityVerification.csproj
Services/CO.CDP.EntityVerification/Program.cs

DP-577: Enable the database connection healthcheck in entity verification

---

Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml

[DP-273](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-273)

Removed address from dash board.

---

Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetPersonInvitesUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetPersonsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateConnectedEntityUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateConnectedEntityUseCase.cs

Fix - Update Connected person creating duplicate address entries

Fix - Update Connected person creating duplicate address entries

---

terragrunt/tools/grafana/configs/dashboards/application/logs-authority.json
terragrunt/tools/grafana/configs/dashboards/application/logs-critical.json
terragrunt/tools/grafana/configs/dashboards/application/logs-data-sharing.json
terragrunt/tools/grafana/configs/dashboards/application/logs-entity-verification-migrations.json
terragrunt/tools/grafana/configs/dashboards/application/logs-entity-verification.json
terragrunt/tools/grafana/configs/dashboards/application/logs-forms.json
terragrunt/tools/grafana/configs/dashboards/application/logs-grafana.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-app.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation-information-migrations.json
terragrunt/tools/grafana/configs/dashboards/application/logs-organisation.json
terragrunt/tools/grafana/configs/dashboards/application/logs-person.json
terragrunt/tools/grafana/configs/dashboards/application/logs-tenant.json

Might be best to review the outcome of this PR which has been rolled out into the development account. perhaps cross checking [dev](https://grafana.dev.supplier.information.findatender.codatt.net/d/critical-logs/critical-logs?orgId=1&from=now-12h&to=now) and [integration](https://grafana.integration.supplier.information.findatender.codatt.net/d/critical-logs/critical-logs?orgId=1&from=now-12h&to=now) which still is on an earlier version.
**Before:**
**After:**

DP-222 Update Grafana application's dashboards

---

Services/CO.CDP.DataSharing.WebApi.Tests/EntityFactory.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/EntityFactory.cs

[DP-516](https://noticingsystem.atlassian.net/browse/DP-516)
Additional test coverage for the Data Sharing API endpoint.

DP-516 BE- Share my information - Data sharing endpoint (API) - Test

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OrganisationSelectionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/OrganisationSelection.cshtml.cs

[DP-231](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-231)

Call Tenant Lookup to get the list of user's organisations

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Users/ClaimOrganisationInviteModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Users/ClaimOrganisationInvite.cshtml.cs

Organisation selection redirect fix

Organisation selection redirect fix

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/database/locals.tf
terragrunt/modules/database/rds-entity-verification.tf
terragrunt/modules/database/rds-sirsi.tf
terragrunt/modules/database/variables.tf
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/variables.tf

- Enable diagnostics in integration

DP-524 Lift the is_production flag to main config

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs

DP-490 bug fix: not updating VAT Number to No.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Helper.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs

DP-490. Further fix required following testing.

DP-490 VAT number - further fix required.

---

terragrunt/components/orchestrator/canary/terragrunt.hcl
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/orchestrator/canary/datasource.tf
terragrunt/modules/orchestrator/canary/iam.tf
terragrunt/modules/orchestrator/canary/locals.tf
terragrunt/modules/orchestrator/canary/main.tf
terragrunt/modules/orchestrator/canary/security-groups.tf
terragrunt/modules/orchestrator/canary/ssm.tf
terragrunt/modules/orchestrator/canary/variables.tf
terragrunt/tools/canary/src/python/canary_check_api.py

This is only to create all the required resources.
In the next PR, we will address the mismatching version expectations along other fine tunings

DP-532 Provision canaries for all accounts

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/orchestrator/canary/cloudwatch.tf
terragrunt/modules/orchestrator/canary/variables.tf

- Reduce canary executions for the time being

DP-532 Enable alarms

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Users/AddUserTests.cs
Frontend/CO.CDP.OrganisationApp/Constants/OrganisationPersonScopes.cs
Frontend/CO.CDP.OrganisationApp/Pages/Users/AddUser.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Users/UserCheckAnswers.cshtml

[DP-586](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-586)

Add the “RESPONDER” scope to new users that are added via User Management.

---

Libraries/CO.CDP.Authentication.Tests/Authorization/OrganisationScopeAuthorizationHandlerTests.cs
Libraries/CO.CDP.Authentication.Tests/ClaimServiceTests.cs
Libraries/CO.CDP.Authentication/Authorization/OrganisationScopeAuthorizationHandler.cs
Libraries/CO.CDP.Authentication/ClaimService.cs
Libraries/CO.CDP.Authentication/Extensions.cs
Libraries/CO.CDP.Authentication/IClaimService.cs
Services/CO.CDP.DataSharing.WebApi.Tests/Api/DataSharingTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/CO.CDP.DataSharing.WebApi.Tests.csproj
Services/CO.CDP.DataSharing.WebApi.Tests/PdfGenerator/PdfGeneratorTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GenerateShareCodeUseCaseTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataPdfUseCaseTests.cs
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/DataService/DataMappingFactory.cs
Services/CO.CDP.DataSharing.WebApi/Extensions/ServiceCollectionExtensions.cs
Services/CO.CDP.DataSharing.WebApi/Model/Exceptions.cs
Services/CO.CDP.DataSharing.WebApi/Model/SharedSupplierInformation.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GenerateShareCodeUseCase.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataPdfUseCase.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/BuyerInformationEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/ConnectedEntityEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationLookupEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/PersonInvitesEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/PersonsEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/SupplierInformationEndpointsTests.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IOrganisationRepository.cs
Services/CO.CDP.Tenant.WebApi/Program.cs
TestKit/CO.CDP.TestKit.Mvc/TestAuthorizationWebApplicationFactory.cs

Part 3: Data Sharing API endpoints authorization

Part 3: Data Sharing API endpoints authorization

---

terragrunt/modules/api-gateway/locals.tf
terragrunt/modules/api-gateway/templates/landing-page.html.tftpl

DP-632 Include Direct URLs for all services in the API's landing page

---

Frontend/CO.CDP.OrganisationApp/Pages/ApiKeyManagement/CreateApiKey.cshtml

back link fix - API key management

---

Frontend/CO.CDP.OrganisationApp/Pages/ApiKeyManagement/ManageApiKey.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/ApiKeyManagement/NewApiKeyDetails.cshtml

DP-256 changed wording from Revoke to Cancel

changed wording from Revoke to Cancel

---

terragrunt/README.md
terragrunt/modules/ecs/datasource.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl

DP-639 Add Companies House secrets to organisation-app

---

terragrunt/components/terragrunt.hcl

Keep **Staging** at version `0.4.0-00c72999` during pen testing

Release-0.5.0 Pin application version 0.5.0 in integration

---

Frontend/CO.CDP.OrganisationApp/Constants/ErrorMessagesList.cs
Frontend/CO.CDP.OrganisationApp/Pages/ApiKeyManagement/NewApiKeyDetails.cshtml
Services/CO.CDP.Organisation.WebApi.Tests/Api/ManageApiKeyEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs

Api key - Web api permission and error message fix

Api key - Web api permission and error message fix

---

Frontend/CO.CDP.OrganisationApp/Pages/Support/Organisations.cshtml

fix for runtime error

---

Frontend/CO.CDP.OrganisationApp/Pages/Users/AddUser.cshtml.cs

https://noticingsystem.atlassian.net/browse/DP-635
Use email regex.

DP-635 - Fix error caused by emails notify classes as invalid - 

---

terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl

DP-193 Add OrganisationApiUrl to set Org's API self address

---

terragrunt/modules/core-iam/telemetry-datasource.tf
terragrunt/tools/grafana/configs/dashboards/application/logs-grafana.json

DP-658 Allow Grafana describe all regions

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormsLandingPageTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsLandingPage.cshtml.cs

Fixed create share code journey navigation

Fixed create share code journey navigation

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementFileUploadModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementFileUploadModel.cs

Fix file re-upload validation

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsQuestionPage.cshtml

Form Save - double click prevent

Form Save - double click prevent

---

Frontend/CO.CDP.OrganisationApp/AuthenticatedSessionAwareMiddleware.cs
Frontend/CO.CDP.OrganisationApp/Program.cs

Anonymous health endpoint access

Anonymous health endpoint access

---

.github/workflows/build.yml
Dockerfile
Makefile
compose.yml
terragrunt/modules/ecs/templates/task-definitions/authority.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/data-sharing.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/entity-verification.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/forms.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/organisation.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/person.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/tenant.json.tftpl

```
make build-docker VERSION=0.5.3
```

Encode the application version inside the Docker image

---

Libraries/CO.CDP.Authentication.Tests/Authorization/OrganisationAuthorizationPolicyProviderTests.cs
Libraries/CO.CDP.Authentication.Tests/Authorization/OrganisationAuthorizeAttributeTests.cs
Libraries/CO.CDP.Authentication.Tests/Authorization/OrganisationScopeAuthorizationHandlerTests.cs
Libraries/CO.CDP.Authentication/Authorization/OrganisationAuthorizationPolicyProvider.cs
Libraries/CO.CDP.Authentication/Authorization/OrganisationAuthorizeAttribute.cs
Libraries/CO.CDP.Authentication/Authorization/OrganisationScopeAuthorizationHandler.cs
Libraries/CO.CDP.Authentication/Authorization/OrganisationScopeAuthorizationRequirement.cs
Libraries/CO.CDP.Authentication/Constants.cs
Services/CO.CDP.Organisation.Authority.Tests/EndpointTest.cs
Services/CO.CDP.Organisation.Authority.Tests/TokenServiceTest.cs
Services/CO.CDP.Organisation.Authority/Endpoint.cs
Services/CO.CDP.Organisation.Authority/Program.cs
Services/CO.CDP.Organisation.Authority/TokenService.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/Api/SupportEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationsUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
TestKit/CO.CDP.TestKit.Mvc/TestAuthorizationWebApplicationFactory.cs

API permission - Person role - SupportAdmin

API permission - Person role - SupportAdmin

---

Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetShareCodeVerifyUseCaseTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetShareCodeVerifyUseCase.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseShareCodeRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IShareCodeRepository.cs

Fixed - Organisation API Key Authorisation

Fixed - Organisation API Key Authorisation

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml

Add link to procurement pathway website from buyer overview screen

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateSupplierInformationUseCase.cs

[DP-683](https://noticingsystem.atlassian.net/browse/DP-683)

DP-683 - Fixed completion of supplier VAT.

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersIndividualOrTrust.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityDirectorResidency.cshtml

Connected Person - Trusts - Incorrect Country List

Connected Person - Trusts - Incorrect Country List

---

terragrunt/tools/grafana/configs/dashboards/application/logs-authority.json

DP-716 Correct authority dashboard log-group

---

terragrunt/tools/grafana/configs/dashboards/application/5xx-across-all-services.json

- Target 5xx status code for this example (last 7 days, but adjustable)
[Tested in staging](https://grafana.staging.supplier.information.findatender.codatt.net/d/de0yee1n9c6bkb/5xx-across-all-services?orgId=1)

BAU-POC Sample dashboard to demonstrate cloudwatch aggregation functions

---

Frontend/CO.CDP.OrganisationApp/Helper.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml

[DP-721](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-721)

DP-721 - hide VAT number on org info screen.

---

Frontend/CO.CDP.OrganisationApp/UserInfoService.cs

Correctly interpret viewer requirement

Correctly interpret viewer requirement

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/_FormElementUrlInput.cshtml

Fix markup rendering in form url input

---

Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml

Common Header - Integration related

Common Header - Integration related

---

terragrunt/tools/grafana/Dockerfile
terragrunt/tools/grafana/configs/dashboard.yaml
terragrunt/tools/grafana/configs/dashboards/overview/service-logs.json
terragrunt/tools/grafana/configs/dashboards/overview/status-code-hits.json
terragrunt/tools/grafana/configs/entrypoint.sh
terragrunt/tools/grafana/configs/grafana.ini

DP-729 Add overview dashboards

---

Services/CO.CDP.Organisation.WebApi.Tests/UseCase/SupportUpdateOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/UseCase/SupportUpdateOrganisationUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs

This way it will be possible to sign up with multiple roles (ones that require approval and ones that do not).

DP-724: Append roles instead of replacing them

---

Services/CO.CDP.DataSharing.WebApi/AutoMapper/DataSharingProfile.cs
Services/CO.CDP.DataSharing.WebApi/Model/Form.cs

Instead of "2024-10-21T14:22:40.852178" we will now have "2024-10-21T14:22:40.852178+00:00".

DP-733: Ensure submittedAt is formatted according to the ISO-8601 standard

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/0.6.1
https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/0.6.2

Release-0.6.2 Pin application version 0.6.2 in staging

---

terragrunt/modules/orchestrator/ci/pipeline.tf

[DP-748](https://noticingsystem.atlassian.net/browse/DP-748)

DP-748 Remova Integration's manual deployment approval

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/0.6.2

Release-0.6.2 Pin application version 0.6.2 in integration

---

terragrunt/components/terragrunt.hcl

This update is to ensure the code is aligned with the account configuration. Version 0.7.0 is already deployed in production.
Due to pre-production accounts being inaccessible from CO's laptop, production (with the approved product domain) serves as the contingency plan for today's activities.

Release-0.7.0 Pin application version 0.7.0 in production

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementDateInputModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementTextInputModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementUrlInputModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementDateInputModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementTextInputModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementUrlInputModel.cs

Fixed - forms answer no selection value display

Fixed - forms answer no selection value display

---

Frontend/CO.CDP.OrganisationApp/Pages/ApiKeyManagement/ManageApiKey.cshtml

cancel an API code named with special characters gets 'page not found'

DP-736 - cancel an API code named with special characters gets 'page not found'

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementUrlInputModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementUrlInputModel.cs

Fixed - form website input validation

Fixed - form website input validation

---

terragrunt/components/terragrunt.hcl

* Registration - Request to Join Organisation
* Support - Beta Feedback Banner & Contact us in footer
* [Bug fix] Form question order
* [Bug fix] Fixed - Exclusions - "exclusion applies" not displaying
* [Bug fix] Exclusions - Submission with a connected person
https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/0.7.0

Release-0.7.0 Pin application version 0.7.0 in integration

---

Frontend/CO.CDP.OrganisationApp/Program.cs

As requested by @webit4me, see https://noticingsystem.atlassian.net/browse/DP-723?focusedCommentId=27796

DP-723: Disable Persisting keys to AWS SSM

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/1.0.1
* User Management - Notify Approve User invited to join
* Content updates to buyer registration journey
* Cookie banner
* Bugfixes
* DO-247
* DP-268
* DP-691
* DP-696
* DP-723
* DP-747
* DP-763
* DP-247
* DP-268

Release-1.0.1 Pin application version 1.0.1 in staging

---

terragrunt/components/external/external.hcl
terragrunt/components/external/networking/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/external-networking/route53.tf
terragrunt/modules/external-networking/variables.tf
terragrunt/modules/telemetry/secrets.tf
terragrunt/modules/tools/secrets.tf

- Added component for external networking to support FTS integration.
- Created CNAME record to route `www.private-beta.find-tender.service.gov.uk` traffic to `nqc-front-door-uksouth.azurefd.net`.

DP-774 Add CNAME Record for FTS and External Networking Component

---

terragrunt/docs/manage-secrets.md
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl

- Update manage-secrets document

DP-770 Add OneLogin's Account URL environment variables

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationRegisterBuyerAsSupplier.cshtml.cs

A little tidying up of the content (pointed out by Stephen - how embarrassing)

Dp 779 quick content fix

---

terragrunt/components/service/tools/terragrunt.hcl
terragrunt/modules/auth/locals.tf
terragrunt/modules/auth/outputs.tf
terragrunt/modules/auth/pgadmin.tf
terragrunt/modules/ecs-service/variables.tf
terragrunt/modules/tools/service-healthcheck.tf
terragrunt/modules/tools/service-pgadmin.tf
terragrunt/modules/tools/variables.tf
terragrunt/tools/pgadmin/README.md

DP-691 Update PGAdmin doc for user managment

DP-505 Put PGAdmin behind Cognito auth

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCheckAnswersOrganisation.cshtml

DP-717 - Legal forms are not getting displayed in summary screen of organisation>Equivalent to register company incompany house no path

DP-717 - Legal forms are not getting displayed in summary screen of organisation>Equivalent to register company incompany house no path

---

terragrunt/modules/orchestrator/ci/pipeline.tf

- Merge staging & integration deployments
**Before:**
**After:**

DP-814 Remove production's manual approval

---

terragrunt/docs/manage-secrets.md
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/orchestrator/ci/pipeline.tf
terragrunt/modules/orchestrator/notification/cloudwatch.tf
terragrunt/modules/orchestrator/notification/datasource.tf
terragrunt/modules/orchestrator/notification/dynamodb.tf
terragrunt/modules/orchestrator/notification/locals.tf
terragrunt/modules/orchestrator/notification/step-function-unified-slack.tf
terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-unified-notification.json.tftpl
terragrunt/modules/orchestrator/notification/variables.tf

Once happy with this, we need to remove the old notification step-function and its relevant components.
**Before:**
**After:**

DP-816 Add unified Slack notifications 

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyRegisterName.cshtml.cs

Connected persons PCS name not pulling through in H1

DP-734 - Connected persons PCS name not pulling through in H1

---

Frontend/CO.CDP.OrganisationApp/Constants/ErrorMessagesList.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/JoinOrganisation.cshtml.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/CreateOrganisationJoinRequestUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/Model/Exceptions.cs
Services/CO.CDP.Organisation.WebApi/UseCase/CreateOrganisationJoinRequestUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationJoinRequestRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IOrganisationJoinRequestRepository.cs

Prevents multiple org join requests for the same user. [DP-811](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-811)

Dp 811 organisation receive multiple joining request

---

terragrunt/modules/tools/service-pgadmin.tf
terragrunt/modules/tools/templates/task-definitions/pgadmin.json.tftpl
terragrunt/tools/pgadmin/configs/custom-entrypoint.sh

DP-691 Bake server configuration's for Kuba and Dharm

---

Frontend/CO.CDP.OrganisationApp.Tests/ApiBearerTokenHandlerTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Authentication/CookieEventsTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Authentication/OneLoginSessionManagerTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/WebApiClients/AuthorityClientTests.cs
Frontend/CO.CDP.OrganisationApp/ApiBearerTokenHandler.cs
Frontend/CO.CDP.OrganisationApp/Authentication/CookieEvents.cs
Frontend/CO.CDP.OrganisationApp/Authentication/IOneLoginAuthority.cs
Frontend/CO.CDP.OrganisationApp/Authentication/IOneLoginSessionManager.cs
Frontend/CO.CDP.OrganisationApp/Authentication/ITokenService.cs
Frontend/CO.CDP.OrganisationApp/Authentication/OidcEvents.cs
Frontend/CO.CDP.OrganisationApp/Authentication/OneLoginAuthority.cs
Frontend/CO.CDP.OrganisationApp/Authentication/OneLoginSessionManager.cs
Frontend/CO.CDP.OrganisationApp/Authentication/TokenService.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/AuthorityClient.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/IAuthorityClient.cs

DP-425 One login Back channel Signing out

DP-425 Part 1 - One login Back channel Signing out

---

Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx
docs/development/cookbooks/02-how-to-localize-ui-text.adoc

[DP-788](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-788)

Added layout header / footer localisation.

---

terragrunt/README.md
terragrunt/docs/manage-secrets.md
terragrunt/modules/tools/secrets.tf
terragrunt/modules/tools/service-pgadmin.tf
terragrunt/modules/tools/templates/task-definitions/pgadmin.json.tftpl

- Document
- This has been rolled out to production and user credentials are shared, ready for testing

DP-691 Fetch PGAdmin's production support users from secrets

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

DP-425 Back channel logout - logging improvement

DP-425 Back channel logout - logging improvement

---

terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl

Tested it a couple of times and seems to be fine, but need to merge and see it running over actual triggers

DP-837 Use retry with back-off rate instead of a second wait

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/AddressPostalSameAsRegisteredQuestion.cshtml

[DP-740](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-740&text=DP-740)

Updated web page as specified in DP-740.

---

terragrunt/modules/orchestrator/notification/templates/state-machine/send-slack-notification.json.tftpl
terragrunt/tools/scripts/trigger_slack_notification_step_function.sh

- Add script to test multiple ntifications with incorrect order

DP-837 Prevent changin final states to Pending Or Start

---

terragrunt/tools/pgadmin/configs/custom-entrypoint.sh

DP-873 Unlock PGAdmin users when new container starts

---

README.md
terragrunt/README.md
terragrunt/docs/diagrams.md

DP-641 Add links to Infra & Diagram Docs.

---

terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl

This will correct the duplicated variables came in with https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/940 while keeping the better naming

DP-867 Correct Task template's variables

---

Services/CO.CDP.EntityVerification/appsettings.json
terragrunt/modules/ecs/service-entity-verification.tf
terragrunt/modules/ecs/templates/task-definitions/entity-verification.json.tftpl

- Add `Features__UuidPponService` to `entity verification` service
- Set it to `false`  in all accounts

DP-870 UUID PPON Service Flag

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/AddressPostalSameAsRegisteredQuestion.cshtml

DP-916 - Incorrect navigation in the 'Does your organization have a different postal address?' page when 'Yes' is selected

DP-916 - Incorrect navigation in the 'Does your organization have a different postal address?' page when 'Yes' is selected

---

Frontend/CO.CDP.OrganisationApp/Authentication/OidcEvents.cs
Frontend/CO.CDP.OrganisationApp/ExceptionMiddleware.cs

dp-866 - correlation cookie - state logging

dp-866 - correlation cookie - state logging

---

Frontend/CO.CDP.OrganisationApp.Tests/Authentication/LogoutManagerTests.cs
Frontend/CO.CDP.OrganisationApp/Authentication/LogoutManager.cs
Frontend/CO.CDP.OrganisationApp/Authentication/OneLoginAuthority.cs
Frontend/CO.CDP.OrganisationApp/Program.cs
Frontend/CO.CDP.OrganisationApp/appsettings.json

dp-889 forward logout notification

dp-889 forward logout notification

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/ecs/load-balancer.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/elasticache/cloudwatch.tf
terragrunt/modules/elasticache/datasource.tf
terragrunt/modules/elasticache/redis.tf
terragrunt/modules/elasticache/secrets.tf
terragrunt/modules/elasticache/variables.tf
terragrunt/modules/externals/database/locals.tf
terragrunt/modules/rds-cluster/parameter-groups.tf
terragrunt/modules/rds-cluster/rds-cluster.tf

- FMT, Apply terraform format
- Allow TLS 1.3

DP-889 Update development's OneLogin logout notification URLs

---

terragrunt/tools/grafana/configs/dashboards/application/5xx-across-all-services.json
terragrunt/tools/grafana/configs/dashboards/infrastructure/redis-logs.json
terragrunt/tools/grafana/configs/dashboards/infrastructure/redis-metrics.json
terragrunt/tools/grafana/configs/entrypoint.sh

This has been deployed and tested in staging:

DP-925 Add Telemetry for Redis

---

Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Frontend/CO.CDP.OrganisationApp/wwwroot/css/site.css

Lift 'test site' banner from FTS

---

Services/CO.CDP.EntityVerification.Tests/Ppon/PponServiceTests.cs
Services/CO.CDP.EntityVerification/Ppon/PponService.cs

[DP-981](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-981)

Updated PPON ID format.

---

Libraries/CO.CDP.Configuration.Tests/Helpers/ConnectionStringHelperTests.cs
Libraries/CO.CDP.Configuration/Helpers/ConnectionStringHelper.cs
Services/CO.CDP.DataSharing.WebApi/appsettings.json
Services/CO.CDP.EntityVerification/appsettings.json
Services/CO.CDP.Forms.WebApi/appsettings.json
Services/CO.CDP.Organisation.Authority/appsettings.json
Services/CO.CDP.Organisation.WebApi/appsettings.json
Services/CO.CDP.Person.WebApi/appsettings.json
Services/CO.CDP.Tenant.WebApi/appsettings.json

dp-989 introduce database connection pool setting

dp-989 introduce database connection pool setting

---

Services/CO.CDP.DataSharing.WebApi/appsettings.json
Services/CO.CDP.EntityVerification/appsettings.json
Services/CO.CDP.Forms.WebApi/appsettings.json
Services/CO.CDP.Organisation.Authority/appsettings.json
Services/CO.CDP.Organisation.WebApi/appsettings.json
Services/CO.CDP.Person.WebApi/appsettings.json
Services/CO.CDP.Tenant.WebApi/appsettings.json

dp-992 Revert connection pool to default

dp-992 Revert connection pool to default

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml

https://noticingsystem.atlassian.net/browse/DP-945?focusedCommentId=28998

Hide devolved regions if there are no devolved regulations set

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml

https://noticingsystem.atlassian.net/browse/DP-98

Only display register as supplier if the buyer org user has admin

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAnswerSetRemoveConfirmation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAnswerSetSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsCheckFurtherQuestionsExempted.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

https://noticingsystem.atlassian.net/browse/DP-995

DP-995 - Add translations to forms view models

---

terragrunt/components/core/networking/terragrunt.hcl
terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/modules/core-iam/terraform-global-datasource.tf
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/core-networking/locals.tf
terragrunt/modules/core-networking/outputs.tf
terragrunt/modules/ecs/load-balancer.tf
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/variables.tf

- Disable rules were preventing login

DP-1002 Assotiate WAF and ALB

---

Frontend/CO.CDP.OrganisationApp.Tests/UserInfoServiceTest.cs
Frontend/CO.CDP.OrganisationApp/IUserInfoService.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/UserInfoService.cs

dp-931 Informal Consortium - list my consortiums

dp-931 Informal Consortium - list my consortiums

---

Frontend/CO.CDP.OrganisationApp/Pages/Cookies.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyPolicy.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/PrivacyPolicy.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/ProvideFeedbackAndContact.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/ProvideFeedbackAndContact.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-999](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-999)

Add translations to cookies, privacy policy and feedback view models

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumChangeNameModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumOverview.cshtml

DP-862 Consortium change name

---

terragrunt/README.md
terragrunt/docs/manage-secrets.md
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/core-networking/datasource.tf
terragrunt/modules/core-networking/locals.tf
terragrunt/modules/core-networking/waf.tf
terragrunt/modules/ecs/locals.tf
terragrunt/tools/grafana/configs/dashboards/infrastructure/waf-blocked-requests.json

- Disable WAF in Integration
- Exclude known IPs to each environment
- Enable AWS Known Bad Inputs Rule
- Document secret management
- Add Grafana dashboard to monitor blocked clients

DP-1002 Fine tuning WAF

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumChangeEmailModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeEmail.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeEmail.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEmail.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/appsettings.AwsDevelopment.json
Services/CO.CDP.Localization/StaticTextResource.resx

DP-947 - Informal Consortium - changing the contact email

DP-947 - Informal Consortium - changing the contact email

---

Frontend/CO.CDP.OrganisationApp.Tests/WebApiClients/AuthorityClientTests.cs
Frontend/CO.CDP.OrganisationApp/Session.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/AuthorityClient.cs

DP-1021 Clear auth tokens after log out

DP-1021 Clear auth tokens after log out

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumChangeAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumChangeAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumOverview.cshtml

DP-946 Consortium Change Address

DP-946 Consortium Change Address

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationType.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLawEnforce.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityLegalFormQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityPscDetails.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

https://noticingsystem.atlassian.net/browse/DP-996
https://noticingsystem.atlassian.net/browse/DP-997

DP-996, DP-997 - Add translations organisation type and connected persons

---

Services/CO.CDP.Localization/StaticTextResource.resx

Fix translation showing <br/> on the page

---

Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20241218164441_OrganisationTypeEnumUpdate.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20241218164441_OrganisationTypeEnumUpdate.cs

DP-1029 - Create migration to update OrganisationTypeEnum

DP-1029 - Create migration to update OrganisationTypeEnum

---

Services/CO.CDP.EntityVerification.Tests/Ppon/PponServiceTests.cs
Services/CO.CDP.EntityVerification/Ppon/UuidPponService.cs
Services/CO.CDP.EntityVerification/Program.cs
Services/CO.CDP.EntityVerification/appsettings.json
terragrunt/modules/ecs/templates/task-definitions/entity-verification.json.tftpl

[DP-917](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-917)

Removed Features__UuidPponService feature flag.

---

Libraries/CO.CDP.Authentication.Tests/ClaimServiceTests.cs
Libraries/CO.CDP.Authentication/ClaimService.cs
Libraries/CO.CDP.Authentication/IClaimService.cs
Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/Api/DataSharingTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/Program.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataUseCase.cs

DP-1044 Enable get share code Info endpoint for onelogin channel

DP-1044 Enable get share code Info endpoint for onelogin channel

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseOrganisationRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseConnectedEntityRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs

[DP-1033](https://noticingsystem.atlassian.net/browse/DP-1033)

DP-1033 - Fixed PDF and DataSharing API where deleted connected person were being returned.

---

Libraries/CO.CDP.DataSharing.WebApiClient.Tests/DataSharingClientIntegrationTest.cs
Services/CO.CDP.DataSharing.WebApi.Tests/Api/DataSharingTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs
Services/CO.CDP.DataSharing.WebApi/Program.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataUseCase.cs

DP-1044 Get org info by Share code without any restriction

DP-1044 Get org info by Share code without any restriction

---

Services/CO.CDP.DataSharing.WebApi/Program.cs
Services/CO.CDP.Forms.WebApi/Program.cs
Services/CO.CDP.Organisation.Authority/Program.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.OrganisationInformation.Persistence/EntityFrameworkCore/NpgsqlDataSourceBuilderExtensions.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250106170559_OrganisationParties.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250106170559_OrganisationParties.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationParty.cs
Services/CO.CDP.Person.WebApi/Program.cs
Services/CO.CDP.Tenant.WebApi/Program.cs

DP-1045 organisation parties persistence

DP-1045 organisation parties persistence

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

DP-1035 dynamic fts return url

DP-1035 dynamic fts return url

---

Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationPartiesEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/AddOrganisationPartyUseCaseTests.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/GetOrganisationPartiesUseCaseTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/ErrorCodes.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Model/Exceptions.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/AddOrganisationPartyUseCase.cs

DP-1045 Add consortium organisation endpoint

DP-1045 Add consortium organisation endpoint

---

terragrunt/modules/orchestrator/ecr/locals.tf
terragrunt/modules/orchestrator/ecr/variables.tf

These are changes missed from my earlier PR https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/1122 , most likely when updating PR with main, so was easy enough to cherry-pick them from the local history

DP-1056 Add missing ECR configs

---

Services/CO.CDP.Localization/StaticTextResource.resx

INTEGREAT-134 Registry name update

INTEGREAT-134 Registry name update

---

Services/CO.CDP.EntityVerification/Ppon/PponService.cs

[DP-1058](https://noticingsystem.atlassian.net/browse/DP-1058)

DP-1058 - Characters: 'B' and 'C' are not allowed as the last character of PPON IDs

---

Frontend/CO.CDP.OrganisationApp/Constants/FeatureFlags.cs
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Layout.cshtml
Frontend/CO.CDP.OrganisationApp/appsettings.AwsIntegration.json
Frontend/CO.CDP.OrganisationApp/appsettings.json

Adding feature flag to allow fts redirect links display

Adding feature flag to allow fts redirect links display

---

Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationMouEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs

Get mou latest endpoint - relax permission for viewer

Get mou latest endpoint - relax permission for viewer

---

Services/CO.CDP.Organisation.WebApi.Tests/Api/OrganisationMouEndpointsTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs

Get latest mou endpoint - Support Admin access

Get latest mou endpoint - Support Admin access

---

terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-organisation-app.tf

[DP-1083](https://noticingsystem.atlassian.net/browse/DP-1083)

DP-1083 Disable Cognito (not WAF) for integration account, doh!

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

Temp code for onelogin user info retrieval

Temp code for onelogin user info retrieval

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

Revert Onelogin user info temp code

Revert Onelogin user info temp code

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumEnterSharecodeModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterSharecode.cshtml.cs

Informal Consortium- Add additional organisations : is accepting duplicate Orgs, Not able to add Organisations belongs another admin

DP-1078 - Informal Consortium-Bug fix

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormsQuestionPageModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/ScanFile.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsQuestionPage.cshtml.cs
Libraries/CO.CDP.GovUKNotify/GovUKNotifyApiClient.cs
Makefile
Services/CO.CDP.AntiVirusScanner.Tests/ScannerTests.cs
Services/CO.CDP.AntiVirusScanner/CO.CDP.AntiVirusScanner.csproj
Services/CO.CDP.AntiVirusScanner/Program.cs
Services/CO.CDP.AntiVirusScanner/Scanner.cs
Services/CO.CDP.AntiVirusScanner/appsettings.Development.json
Services/CO.CDP.AntiVirusScanner/appsettings.json
compose.override.yml.template
terragrunt/modules/ecs/service-av-scanner-app.tf
terragrunt/modules/ecs/templates/task-definitions/av-scanner-app.json.tftpl

[DP-1041](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1041)

DP-1041 - Send email to user and org email if virus scanning fails

---

Libraries/CO.CDP.DataSharing.WebApiClient/CO.CDP.DataSharing.WebApiClient.csproj
Services/CO.CDP.DataSharing.WebApi/Api/DataSharing.cs

Consortium - Unable to add an organisation to the consortium

Consortium - Unable to add an organisation to the consortium

---

Services/CO.CDP.Forms.WebApi.Tests/UseCase/UpdateFormSectionAnswersUseCaseTest.cs
Services/CO.CDP.Forms.WebApi/UseCase/UpdateFormSectionAnswersUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/Factories/SharedConsentFactory.cs

DP-1097 New exclusions not showing

DP-1097 New exclusions not showing

---

terragrunt/modules/core-networking/waf.tf
terragrunt/tools/grafana/configs/dashboards/infrastructure/waf-overview.json

DP-1111 Remove WAF Log Filter, Add overview dashboard

---

Frontend/CO.CDP.OrganisationApp.Tests/Authentication/CookieEventsTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Shared/PaginationPartialModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/WebApiClients/AuthorityClientTests.cs
Frontend/CO.CDP.OrganisationApp/Authentication/CookieEvents.cs
Frontend/CO.CDP.OrganisationApp/Session.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/AuthorityClient.cs

Authority api access token storage moved to session

Authority api access token storage moved to session

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/ShareInformation/ShareCodeConfirmationTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/ShareInformation/ShareCodeDetailsTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/ShareInformation/ShareCodesListViewTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterSharecode.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodeConfirmation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodeDetails.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodesListView.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

removed null reference warnings for consortium

removed null reference warnings for consortium

---

terragrunt/components/terragrunt.hcl
terragrunt/tools/grafana/configs/dashboards/infrastructure/ecs.json

This has been tested against av-scanner-app and seems fine in production.

DP-1141 Scale up production. Update ECS dashboard

---

Services/CO.CDP.EntityVerification.Tests/Events/EventsFactories.cs
Services/CO.CDP.EntityVerification.Tests/Ppon/OrganisationRegisteredSubscriberTests.cs
Services/CO.CDP.EntityVerification.Tests/Ppon/PponServiceTests.cs
Services/CO.CDP.EntityVerification/Events/InboundEvents.cs
Services/CO.CDP.EntityVerification/Ppon/IPponService.cs
Services/CO.CDP.EntityVerification/Ppon/OrganisationRegisteredSubscriber.cs
Services/CO.CDP.EntityVerification/Ppon/PponService.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/RegisterOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/AutoMapper/WebApiToPersistenceProfile.cs
Services/CO.CDP.Organisation.WebApi/Events/OrganisationRegistered.cs

[DP-1060](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1060)

DP-1060 - PPON - Consortium Code

---

Frontend/CO.CDP.OrganisationApp.Tests/FileUploadMiddlewareTests.cs
Frontend/CO.CDP.OrganisationApp/FileUploadMiddleware.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementFileUploadModel.cs
Frontend/CO.CDP.OrganisationApp/Program.cs

[DP-1024](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1024)

DP-1024 - Uploading a file over 25mb results in error

---

terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/templates/task-definitions/organisation-app.json.tftpl
terragrunt/modules/ecs/variables.tf

- Add FTS service allowed origins env_var

DP-1164 Update integration's logout notification urls

---

terragrunt/components/service/tools/terragrunt.hcl
terragrunt/modules/core-iam/ecs.tf
terragrunt/modules/ecs/outputs.tf
terragrunt/modules/tools/datasource.tf
terragrunt/modules/tools/iam.tf
terragrunt/modules/tools/locals.tf
terragrunt/modules/tools/step-function.tf
terragrunt/modules/tools/templates/state-machine/update-service.json.tftpl
terragrunt/modules/tools/variables.tf

- Correct CloudWatch event role (which might cause issue during deployment)

DP-1170 Implement mechanism to trigger re-deployment of tools

---

terragrunt/components/terragrunt.hcl

DP-992 Scale out dev services to 4

---

terragrunt/tools/grafana/configs/dashboards/application/logs-pgadmin.json

DP-1170 Add PGAdmin logs dashboard

---

terragrunt/components/terragrunt.hcl

DP-1174 Add new services configuration, Provision their ECR

---

Services/CO.CDP.Localization/StaticTextResource.resx

Updated all mention of the registry names and numbers including some error messages and pdf text

DP-1175 - Content changes - Update registry names and numbers including some error messages and pdf text

---

Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataUseCaseTest.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseShareCodeRepositoryTest.cs

DP-1149 Consortium share code endpoint unit test

DP-1149 Consortium share code endpoint unit test

---

terragrunt/modules/tools/task-k6.tf
terragrunt/modules/tools/templates/state-machine/trigger-k6.json.tftpl
terragrunt/modules/tools/templates/task-definitions/k6.json.tftpl
terragrunt/tools/grafana/configs/dashboards/application/logs-k6.json
terragrunt/tools/k6/Dockerfile
terragrunt/tools/k6/README.md
terragrunt/tools/k6/scripts/lib/uuid.js
terragrunt/tools/k6/scripts/main.js
terragrunt/tools/k6/scripts/organisation-lookup.js
terragrunt/tools/k6/scripts/requests/getOrganisations.js
terragrunt/tools/k6/scripts/requests/index.js
terragrunt/tools/k6/scripts/requests/postOrganisations.js

- Update Task and Step Function accordingly
- Update Dashboard

DP-1184 Copy in new tests

---

Libraries/CO.CDP.Authentication/Constants.cs
Services/CO.CDP.Organisation.Authority.Tests/EndpointTest.cs
Services/CO.CDP.Organisation.Authority.Tests/TokenServiceTest.cs
Services/CO.CDP.Organisation.Authority/Endpoint.cs
Services/CO.CDP.Organisation.Authority/TokenService.cs

DP-1188 Authority token optimisation

DP-1188 Authority token optimisation

---

Services/CO.CDP.Localization/FormsEngineResource.resx

key added to 'pending translation' file

Update qualifications hint text

---

Services/CO.CDP.Localization/FormsEngineResource.resx

Keys added to the 'for translation' doc

Update various content in financial information section

---

terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/service-outbox-processor-entity-verification.tf
terragrunt/modules/ecs/service-outbox-processor-organisation.tf
terragrunt/modules/ecs/templates/task-definitions/outbox-processor-entity-verification.json.tftpl
terragrunt/modules/ecs/templates/task-definitions/outbox-processor-organisation.json.tftpl
terragrunt/tools/grafana/configs/dashboards/application/logs-outbox-processor-entity-verification.json
terragrunt/tools/grafana/configs/dashboards/application/logs-outbox-processor-organisation.json
terragrunt/tools/grafana/configs/dashboards/infrastructure/ecs.json

- Add their Grafana dashboards

DP-1174 Configure processor services

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

DP-1022 Sign out redirect to FTS when enabled

DP-1022 Sign out redirect to FTS when enabled

---

terragrunt/components/terragrunt.hcl

Pass dummy values for orchestrator's ECS

BAU Fix Pipeline

---

Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationDetailsSummary.cshtml
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-1182](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1182)

DP-1182 - Added translations for OrganisationDetailsSummary.cshtml

---

terragrunt/components/service/cache/terragrunt.hcl
terragrunt/components/terragrunt.hcl
terragrunt/modules/database/rds-sirsi.tf
terragrunt/modules/db-postgres-cluster/rds-cluster.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/elasticache/redis.tf
terragrunt/tools/grafana/configs/dashboards/overview/system-perf.json

- Scale up Redis
- Add performance dashbard (WIP)

DP-506 Scale up Production to what was tested in Staging

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationNameModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationName.cshtml.cs

https://noticingsystem.atlassian.net/browse/DP-1196

DP-1196 - Remove extra inner spaces in organisation name when registering

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/SignedOutModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/SignoutPage.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/SignoutPage.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1228 Create signedout url page

DP-1228 Create signedout url page

---

terragrunt/components/external/networking/terragrunt.hcl
terragrunt/components/service/api-gateway/terragrunt.hcl
terragrunt/components/service/auth/terragrunt.hcl
terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/components/service/telemetry/terragrunt.hcl
terragrunt/components/service/tools/terragrunt.hcl
terragrunt/modules/core-networking/outputs.tf
terragrunt/modules/ecs/locals.tf
terragrunt/modules/ecs/outputs.tf
terragrunt/modules/ecs/route53.tf
terragrunt/modules/ecs/variables.tf
terragrunt/modules/telemetry/locals.tf
terragrunt/modules/telemetry/route53.tf
terragrunt/modules/telemetry/variables.tf
terragrunt/modules/tools/locals.tf
terragrunt/modules/tools/route53.tf
terragrunt/modules/tools/service-clamav-rest.tf
terragrunt/modules/tools/variables.tf
terragrunt/tools/grafana/configs/dashboards/overview/system-performance.json
terragrunt/tools/grafana/configs/grafana.ini

- Update system-performance dashboard

DP-1069 Clean up dual domain logic

---

terragrunt/components/service/ecs/terragrunt.hcl
terragrunt/modules/core-iam/terraform-global-datasource.tf
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/core-networking/outputs.tf
terragrunt/modules/ecs/acm.tf
terragrunt/modules/ecs/load-balancer.tf
terragrunt/modules/ecs/variables.tf

- Add certificates for live and  private-beta domain
- Grant permission to attach additional certs to the load-balancer

DP-1069 Switch to live domain

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Forms/FormElementAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Organisation/OrganisationRegisteredAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp/Models/Address.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormElementAddressModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/RegistrationStepModel.cs
Frontend/CO.CDP.OrganisationApp/Pages/Shared/AddressPartialModel.cs
Services/CO.CDP.DataSharing.WebApi/Model/ConnectedPersonInformation.cs
Services/CO.CDP.Forms.WebApi/Model/FormAnswer.cs
Services/CO.CDP.Forms.WebApi/UseCase/UpdateFormSectionAnswersUseCase.cs
Services/CO.CDP.Organisation.WebApi/Events/Values.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.OrganisationInformation.Persistence/Address.cs
Services/CO.CDP.OrganisationInformation.Persistence/Forms/FormAnswer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250220152828_PostalCodeNuallable.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250220152828_PostalCodeNuallable.cs
Services/CO.CDP.OrganisationInformation/Address.cs

DP-1098 Optional postcode for non-uk address

DP-1098 Optional postcode for non-uk address

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateOrganisationUseCaseTest.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateOrganisationUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250225102501_IdentifierSchemaUniqueIndex.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250225102501_IdentifierSchemaUniqueIndex.cs
Services/CO.CDP.OrganisationInformation.Persistence/Organisation.cs

DP-1250 Allow same vat for multiple orgs

DP-1250 Allow same vat for multiple orgs

---

terragrunt/components/service/tools/terragrunt.hcl
terragrunt/modules/alerting/locals.tf
terragrunt/modules/alerting/sns.tf
terragrunt/modules/alerting/variables.tf
terragrunt/modules/core-iam/terraform-product-datasource.tf

Grant terraform permission to manage SNS

DP-1270 Add Alerting componenet, provision topic

---

terragrunt/modules/alerting/alerts-ecs.tf
terragrunt/modules/alerting/datasource.tf
terragrunt/modules/alerting/iam.tf
terragrunt/modules/alerting/locals.tf
terragrunt/modules/alerting/variables.tf
terragrunt/modules/core-iam/terraform-product-datasource.tf

- Early merge to provision IAM changes, unblocking pipeline

DP-1270 (WIP) Scaffold ECS CUP alerts

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Mou/MoUSummaryModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/MoU/MoUSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/MoU/MoUSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationSelection.cshtml
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1010 - MOU - Buyer Registration - MoU Summary Page

DP-1010 - MOU - Buyer Registration - MoU Summary Page

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Organisation/SupplierToBuyerOrganisationDetailsSummaryTest.cs
Frontend/CO.CDP.OrganisationApp/Models/SupplierToBuyerDetails.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerOrganisationDetailsSummary.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerOrganisationType.cshtml.cs
Frontend/CO.CDP.OrganisationApp/WebApiClients/OrganisationClientExtensions.cs

DP-1180 - Supplier-to-buyer : Validations are missing for ' Other/Enter type' on the supplier-to-buyer-organisation-type page

DP-1180 - Supplier-to-buyer : Validations are missing for ' Other/Enter type' on the supplier-to-buyer-organisation-type page

---

terragrunt/components/terragrunt.hcl

Reverts cabinetoffice/GCGS-Central-Digital-Platform#1394

Revert "Temporarily shipping #1366 to staging for load testing"

---

terragrunt/modules/alerting/alarm-ecs-errors.tf
terragrunt/modules/alerting/alarm-sqs.tf
terragrunt/modules/alerting/sns.tf

- Remove insufficient_data_actions from SQS alerts
- Comment out 4xx

DP-1270 Split app errors into separate queue

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseConnectedEntityRepositoryTests.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseConnectedEntityRepository.cs

DP-1233 - UI - Connected Person - Display first name & last name

DP-1233 - UI - Connected Person - Display first name & last name

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationNameSearchTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNameSearch.cshtml.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs

[DP-1195](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1195)

DP-1195 - Buyer search redirects to join-organisation for pending buyer with same name

---

.github/workflows/build.yml
E2ETests/Dockerfile
E2ETests/E2ETests.cs
E2ETests/E2ETests.csproj
E2ETests/compose.yml
Makefile

- Branch of from @FarzanGoaco [forked PR](https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/pull/1393)
- Add stage to the build workflow
- Use docker host with a fall back to cover both flavours
- Remove version directive

DP-1261 E2E & UI testing framework

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerSelectDevolvedRegulation.cshtml
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-1161](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1161)

DP-1161 - Updated supplier to buyer devolved regulation check boxes to radio buttons

---

Frontend/CO.CDP.OrganisationApp/Pages/MoU/MoUSummary.cshtml
Services/CO.CDP.Localization/StaticTextResource.resx
Services/CO.CDP.Organisation.WebApi/UseCase/CreateOrganisationSignMouUseCase.cs

[DP-1284](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?assignee=712020%3Abb9d1421-c744-4359-bc93-648cdc5a5c0e&selectedIssue=DP-1284)

DP-1284 - MoU - Summary Screen - Add additional field

---

Services/CO.CDP.EntityVerification.Persistence/DatabasePponRepository.cs

[DP-1298](https://noticingsystem.atlassian.net/browse/DP-1298)

DP-1298 - Improved performance of FindPponByIdentifierAsync 

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityRemoveConfirmationModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityRemoveConfirmation.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

Connected entity end date validation - do not allow today and future date

DP-1312 - Connected entity end date validation

---

Services/CO.CDP.DataSharing.WebApi.Tests/Api/DataSharingApiIntegrationTests.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GenerateShareCodeUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseShareCodeRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseFormRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/IFormRepository.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250315000609_SharedConsentSnapshot.Designer.cs
Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20250315000609_SharedConsentSnapshot.cs
Services/CO.CDP.OrganisationInformation.Persistence/OrganisationInformationContext.cs
Services/CO.CDP.OrganisationInformation.Persistence/SharedConsentSnapshot.cs

Shared consent snapshot tables creation
Populate tables on Share code creation
Update API endpoint to retrieve data from snapshot tables
Existing Share code SQL migration

Shared consent snapshot tables, population, retrieval and migration

---

Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierInformationSummary.cshtml
Services/CO.CDP.Localization/FormsEngineResource.resx
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1211 - Content updates and layout tweaks for supplier information page

---

terragrunt/components/terragrunt.hcl

See https://github.com/cabinetoffice/GCGS-Central-Digital-Platform/releases/tag/1.0.47.1

Release 1.0.47.1 to integration

---

Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodesListView.cshtml
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-1273](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1273)

DP-1273 - Updates to layout and text for ShareCodesListView.cshtml

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierEmailAddressTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierVatQuestionTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/SupplierWebsiteModelQuestionTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_Address.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierEmailAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierEmailAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierIndividualOrOrg.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierIndividualOrOrg.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierOperationQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierVatQuestion.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierWebsiteQuestion.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierWebsiteQuestion.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1103 Supplier info content change

DP-1103 Supplier info content change

---

Services/CO.CDP.DataSharing.WebApi.Tests/DataService/DataServiceTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/PdfGenerator/PdfGeneratorTests.cs
Services/CO.CDP.DataSharing.WebApi.Tests/UseCase/GetSharedDataFileUseCaseTests.cs
Services/CO.CDP.DataSharing.WebApi/DataService/DataService.cs
Services/CO.CDP.DataSharing.WebApi/IPdfGenerator.cs
Services/CO.CDP.DataSharing.WebApi/Model/SharedSupplierInformation.cs
Services/CO.CDP.DataSharing.WebApi/PdfGenerator.cs
Services/CO.CDP.DataSharing.WebApi/UseCase/GetSharedDataFileUseCase.cs
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1151 - Informal Consortium - PDF Generation

DP-1151 - Informal Consortium - PDF Generation

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Organisation/SupplierToBuyerDevolvedRegulationTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Organisation/SupplierToBuyerSelectDevolvedRegulationTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerDevolvedRegulation.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerOrganisationDetailsSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerOrganisationType.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerSelectDevolvedRegulation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/SupplierToBuyerSelectDevolvedRegulation.cshtml.cs

DP-1238 - Buyer - Change devolved Regs

DP-1238 - Buyer - Change devolved Regs

---

Frontend/CO.CDP.OrganisationApp/Pages/ContactUs.cshtml

DP - 1345 - WCAG A - Page title - contact us page

DP - 1345 - WCAG A - Page title - contact us page

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsAnswerSetSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationSelection.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedPersonSummary.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/SupplierBasicInformation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Users/UserCheckAnswers.cshtml
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx
terragrunt/components/terragrunt.hcl

https://noticingsystem.atlassian.net/browse/DP-1340

DP-1340 - WCAG A - Link purpose in context - change / add links

---

Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationRepository.cs

https://noticingsystem.atlassian.net/browse/DP-1374

DP-1374 - Fix Support admin screen is showing duplicate organisations

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationInternationalIdentification.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Shared/_FlashMessage.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Users/AddUser.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/YourDetails.cshtml

DP-1336 - WCAG A - Heading structure

DP-1336 - WCAG A - Heading structure

---

terragrunt/modules/ecs/locals.tf

Reverts cabinetoffice/GCGS-Central-Digital-Platform#1518

BAU enable Send Notify Emails in Development environmnet

---

Frontend/CO.CDP.OrganisationApp/Pages/Index.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/MoU/ReviewAndSignMemorandom.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodeConfirmation.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/ShareInformation/ShareCodeDetails.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Support/OrganisationApproval.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Users/OrganisationInviteExpired.cshtml
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx

GOVUK Link styling - missing class

GOVUK Link styling - missing class

---

Services/CO.CDP.Localization/FormsEngineResource.cy.resx
Services/CO.CDP.Localization/FormsEngineResource.resx

DP-1349 - “or“ is missing

---

terragrunt/components/terragrunt.hcl

Reverts cabinetoffice/GCGS-Central-Digital-Platform#1528

Revert "Pin dev to 1.0.58-754f0213 (Support admin search orgs improvement)"

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/_FormElementDateInput.cshtml

[DP-1341](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1341)

DP-1341 - WCAG A - Aria attributes - exclusion end date

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Organisation/OrganisationIdentificationModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/CompanyHouseNumberQuestionTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationIdentification.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/CompanyHouseNumberQuestion.cshtml.cs
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-1274](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?assignee=712020%3Abb9d1421-c744-4359-bc93-648cdc5a5c0e&selectedIssue=DP-1274)

Companies House number character length must be 8 characters in length.

---

Services/CO.CDP.DataSharing.WebApi/PdfGenerator.cs
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx

[DP-1371](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1371)

DP-1371 - Supplier information PDF - show None apply if user has selected 'no'

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/_FormElementDateInput.cshtml

Reverts cabinetoffice/GCGS-Central-Digital-Platform#1510

Revert "DP-1341 - WCAG A - Aria attributes - exclusion end date"

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumAddressModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumCheckAnswerModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumEmailModelTest.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumNameModelTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumAddress.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumAddress.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumCheckAnswer.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumCheckAnswer.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEmail.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEmail.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumName.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumName.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumStepModel.cs
Services/CO.CDP.Localization/StaticTextResource.resx

DP-1248 - Consortium - Check Your Answers page

DP-1248 - Consortium - Check Your Answers page

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/OneLoginTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/OneLogin.cshtml.cs

DP-1394 Fix Recreate Onelogin while active session error fix

DP-1394 Fix Recreate Onelogin while active session error fix

---

compose.override.yml.template
terragrunt/components/terragrunt.hcl
terragrunt/modules/core-networking/route53.tf

DP-1404 (WIP) Delegate development domain from production, 

---

Services/CO.CDP.OrganisationInformation.Persistence.Tests/DatabaseFormRepositoryTest.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseConnectedEntityRepository.cs

Bug fix for: [DP-1329](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22/backlog?selectedIssue=DP-1329&text=DP-1329)

DP-1329 - Connected Persons bug fix

---

Frontend/CO.CDP.OrganisationApp/Pages/Forms/_FormElementDateInput.cshtml

[DP-1341](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1341)

Fix bug in finance date screen.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/LegalFormSelectOrganisationModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/LegalFormSelectOrganisation.cshtml.cs

https://noticingsystem.atlassian.net/browse/DP-1403

DP-1403 - Fix Legal form - flow switches from CH yes to CH no if error on 'other' input

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Registration/OrganisationNameSearchTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNameSearch.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Registration/OrganisationNameSearch.cshtml.cs

[DP-1421](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1421)

DP-1421 - Fix join organisation on buyer registration page.

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyNotConnectedDateModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Supplier/ConnectedEntity/ConnectedEntityCompanyNotConnectedDate.cshtml.cs

[DP-1456](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1456)

DP-1456 - Date No Longer Connected' page heading is missing When Proceeding Without Input

---

terragrunt/components/terragrunt.hcl

Reverts cabinetoffice/GCGS-Central-Digital-Platform#1582

Revert "Temporarily pin dev to avoid auto deploying latest build from integration branch"

---

E2ETests/Pages/Exclusions/AddExclusionsYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionSummaryPage.cs
E2ETests/Pages/Exclusions/ExclusionsCheckAnswerPage.cs
E2ETests/Pages/Exclusions/ExclusionsDecisionRecordedYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsDeclarationPage.cs
E2ETests/Pages/Exclusions/ExclusionsDescribeInDetailsPage.cs
E2ETests/Pages/Exclusions/ExclusionsEndedYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsEnterEmailPage.cs
E2ETests/Pages/Exclusions/ExclusionsHowBeingManagedPage.cs
E2ETests/Pages/Exclusions/ExclusionsInUKYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsSupportingDocumentsYesNoPage.cs
E2ETests/Pages/Exclusions/SelectExclusionAppliesToPage.cs
E2ETests/Pages/Exclusions/SelectExclusionPage.cs
E2ETests/Tests/Exclusions/ExclusionsBaseTest.cs
E2ETests/Tests/Exclusions/ExclusionsFunctionalTest.cs
E2ETests/Tests/Exclusions/ExclusionsNavigationTest.cs
Frontend/CO.CDP.OrganisationApp/Pages/Exclusions/AddExclusionDeclaration.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Forms/FormsQuestionPage.cshtml

DP-1388 - Test Automation E2E Journey - Add any Exclusions

DP-1388 - Test Automation E2E Journey - Add any Exclusions

---

Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumEnterNewSharecodeModelTests.cs
Frontend/CO.CDP.OrganisationApp.Tests/Pages/Consortium/ConsortiumOverviewModelTests.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterNewSharecode.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterNewSharecode.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterSharecode.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumEnterSharecode.cshtml.cs
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumOverview.cshtml
Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumOverview.cshtml.cs
Frontend/CO.CDP.OrganisationApp/appsettings.Development.json
Services/CO.CDP.Localization/StaticTextResource.resx
Services/CO.CDP.Organisation.WebApi.Tests/UseCase/UpdateOrganisationPartyUseCaseTests.cs
Services/CO.CDP.Organisation.WebApi/Api/Organisation.cs
Services/CO.CDP.Organisation.WebApi/Model/Command.cs
Services/CO.CDP.Organisation.WebApi/Program.cs
Services/CO.CDP.Organisation.WebApi/UseCase/UpdateOrganisationPartyUseCase.cs
Services/CO.CDP.OrganisationInformation.Persistence/DatabaseOrganisationPartiesRepository.cs

[DP-1302](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-1302)

DP-1302 - Consortium - Update Organisations Share Code

---

terragrunt/modules/core-networking/locals.tf
terragrunt/modules/core-networking/waf-tools.tf

- Rmove all other rules, given the default action is block

DP-1474 Allow NAT IP in

---

E2ETests/Tests/OrganisationDetails/AdditionalSupplierInformationModules/HealthAndSafetyTests.cs

CDPDEL-458: Health and Safety - Additional Supplier Information Modules - E2E tests

---

Frontend/CO.CDP.OrganisationApp/Pages/Consortium/ConsortiumStart.cshtml
Services/CO.CDP.Localization/StaticTextResource.cy.resx
Services/CO.CDP.Localization/StaticTextResource.resx

Light content updates to the consortium start page including adding a new paragraph. ConsortiumStart_Paragraph key numbers updated in 3 files and keys added to the pending translation spreadsheet.

Dp 1508 update consortium start page

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/core-iam/terraform-product-datasource.tf
terragrunt/modules/ecs/service-av-scanner-app.tf
terragrunt/modules/ecs/service-fts-healthcheck.tf
terragrunt/modules/ecs/service-fts-scheduler.tf
terragrunt/modules/ecs/service-organisation-app.tf
terragrunt/modules/ecs/service-organisation.tf
terragrunt/modules/ecs/service-outbox-processor-entity-verification.tf
terragrunt/modules/ecs/service-outbox-processor-organisation.tf
terragrunt/modules/ecs/service-person.tf
terragrunt/modules/ecs/service-scheduled-worker.tf
terragrunt/modules/ecs/service-tenant.tf
terragrunt/modules/ecs/templates/task-definitions/fts-scheduler.json.tftpl

- Correct host ports for other services were copied from org-app

DP-1499 Configure FTS scheduler as stand-alone service. Add container healthcheck

---

E2ETests/E2ETests.csproj
E2ETests/Pages/Exclusions/ExclusionSummaryPage.cs
E2ETests/Pages/TradeAssurances/TradeAssurancesCheckYourAnswersPage.cs
E2ETests/Pages/TradeAssurances/TradeAssurancesSummaryPage.cs

E2E Tests fix

---

terragrunt/tools/grafana/configs/dashboards/application/supervisor-fts-app.json

... Even though logs are not populated in the log group yet

DP-1518 Include App's dashboard

---

E2ETests/Pages/Exclusions/AddExclusionsYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsCheckAnswerPage.cs
E2ETests/Pages/Exclusions/ExclusionsDecisionRecordedYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsDescribeInDetailsPage.cs
E2ETests/Pages/Exclusions/ExclusionsEndedYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsEnterEmailPage.cs
E2ETests/Pages/Exclusions/ExclusionsHowBeingManagedPage.cs
E2ETests/Pages/Exclusions/ExclusionsInUKYesNoPage.cs
E2ETests/Pages/Exclusions/ExclusionsSupportingDocumentsYesNoPage.cs
E2ETests/Pages/Exclusions/SelectExclusionAppliesToPage.cs
E2ETests/Pages/Exclusions/SelectExclusionPage.cs

E2ETest exclusion test fix

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/gcgs-cdp-fts-service/releases/tag/1.0.5

Release FTS 1.0.5 to production

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/gcgs-cdp-fts-service/releases/tag/1.0.7

Release FTS 1.0.7 to production

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/gcgs-cdp-fts-service/releases/tag/1.0.8

Release FTS 1.0.8 to production

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/gcgs-cdp-fts-service/releases/tag/1.0.9

Release FTS 1.0.9 to production

---

terragrunt/modules/ecs/locals-cfs.tf
terragrunt/modules/ecs/templates/task-definitions/cfs.json.tftpl

Empty secrets have been injected into all accounts.
This change, to pull those secrets for CFS service have been applied in development account.
If [CFS service in development](cfs.dev.supplier-information.find-tender.service.gov.uk) is fine, PR is safe to merge

DP-1676 Add CFS Lets Encrypt secrets

---

Frontend/CO.CDP.OrganisationApp/Pages/Organisation/OrganisationPponSearch.cshtml

Fixed issue with PPON Search when user navigates to another page other than the first page of results and then the user submits another Search they are not navigated back to the first page of results.

CDPDEL-854: Fixed issue with PPON Search with user not being navigated to first page on new search.

---

terragrunt/components/terragrunt.hcl

https://github.com/cabinetoffice/gcgs-cdp-cfs-service/releases/tag/1.0.4

Release CFS 1.0.4 to integration and production

---

terragrunt/components/terragrunt.hcl
terragrunt/modules/database/rds-fts.tf

- Scale FTS/CFS RDs down in dev, from r5.xlarge to r5.large
- Scale FTS/CFS DBs in to 1 instance in Development

DP-1954 FTS/CFS DB scaling down/in in development
